version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/sdks/python"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/sdks/python"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
