# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Apps resource for managing the authenticated Inttegro application."""
from __future__ import annotations
from ..async_http_client import AsyncHttpClient

class AsyncApps:
    """Application creation, lookup, and update operations."""

    def __init__(self, http: AsyncHttpClient):
        self.http = http

    async def create(self, payload: dict):
        """Create a Inttegro application."""
        return await self.http.post('/apps/create', payload)

    async def lookup(self):
        """Retrieve the application associated with the configured API key."""
        return await self.http.post('/apps/lookup', {})

    async def update(self, payload: dict):
        """Update one or more attributes of the configured API key's application."""
        return await self.http.post('/apps/update', payload)
