# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Generated public typing surface. Do not edit by hand."""
from typing import Any
from ..async_http_client import AsyncHttpClient
from .._models import Application
from ..request_types import *

class AsyncApps:

    def __init__(self, http: AsyncHttpClient) -> None:
        ...

    async def create(self, payload: CreateApplicationRequest) -> Application:
        ...

    async def lookup(self) -> Application:
        ...

    async def update(self, payload: UpdateApplicationRequest) -> Application:
        ...
