# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Generated public typing surface. Do not edit by hand."""
from typing import Any
from ..async_http_client import AsyncHttpClient
from inttegro.balance_transaction.balance_transaction import BalanceTransaction
from inttegro.balance_transaction.page import Page
from inttegro.balance_transaction.page_request import PageRequest

class AsyncBalanceTransactions:

    def __init__(self, http: AsyncHttpClient) -> None:
        ...

    async def lookup(self, transaction_id: str) -> BalanceTransaction:
        ...

    async def page(self, payload: PageRequest | None=None) -> Page:
        ...
