# Generated by scripts/generate_async_resources.py; do not edit by hand.
from __future__ import annotations
from ..async_http_client import AsyncHttpClient

class AsyncBalances:

    def __init__(self, http: AsyncHttpClient):
        self.http = http

    async def get(self):
        return await self.http.post('/balances', {})
