# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Generated public typing surface. Do not edit by hand."""
from typing import Any
from ..async_http_client import AsyncHttpClient
from .._models import BalanceTransaction, BalanceTransactionPage
from ..request_types import *

class AsyncBalanceTransactions:

    def __init__(self, http: AsyncHttpClient) -> None:
        ...

    async def lookup(self, transaction_id: str) -> BalanceTransaction:
        ...

    async def page(self, payload: PageBalanceTransactionsRequest | None=None) -> BalanceTransactionPage:
        ...
