# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Generated public typing surface. Do not edit by hand."""
from typing import Any
from ..async_http_client import AsyncHttpClient
from .._models import BalanceSnapshot
from ..request_types import *

class AsyncBalances:

    def __init__(self, http: AsyncHttpClient) -> None:
        ...

    async def get(self) -> BalanceSnapshot:
        ...
