# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Balance operations for the authenticated Inttegro application."""
from __future__ import annotations
from ..async_http_client import AsyncHttpClient

class AsyncBalances:
    """Read the application's current GHS balance snapshot.

    The returned :class:`inttegro.balance.Balance` has a statically typed
    ``ghs`` member. Amounts use integer minor units and snapshot timestamps are
    decoded as timezone-aware :class:`datetime.datetime` values.
    """

    def __init__(self, http: AsyncHttpClient):
        """Bind the balance operations to the client's shared HTTP transport."""
        self.http = http

    async def get(self):
        """Return the latest balance snapshot for the authenticated application.

        API endpoint: ``/balances``.

        Returns:
            ``Balance`` decoded from the documented response shape.

        Raises:
            APIError: The API rejected the request or could not complete it.
            NetworkError: The request could not reach the Inttegro API.
            TimeoutError: The configured request deadline elapsed.
        """
        return await self.http.post('/balances', {})
