# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Broadcasts resource for looking up and canceling broadcasts."""
from __future__ import annotations
from ..async_http_client import AsyncHttpClient

class AsyncBroadcasts:
    """Broadcasts resource for managing broadcast chimes."""

    def __init__(self, http: AsyncHttpClient):
        self.http = http

    async def lookup(self, broadcast_id: str):
        """Lookup a broadcast by broadcast ID."""
        return await self.http.post('/broadcasts/lookup', {'broadcast_id': broadcast_id})

    async def cancel(self, broadcast_id: str):
        """Cancel a broadcast by broadcast ID."""
        return await self.http.post('/broadcasts/cancel', {'broadcast_id': broadcast_id})
