# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Generated public typing surface. Do not edit by hand."""
from typing import Any
from ..async_http_client import AsyncHttpClient
from inttegro.broadcast.cancel_detail import CancelDetail
from inttegro.broadcast.broadcast import Broadcast

class AsyncBroadcasts:

    def __init__(self, http: AsyncHttpClient) -> None:
        ...

    async def lookup(self, broadcast_id: str) -> Broadcast:
        ...

    async def cancel(self, broadcast_id: str) -> CancelDetail:
        ...
