# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Generated public typing surface. Do not edit by hand."""
from typing import Any
from ..async_http_client import AsyncHttpClient
from .._models import BroadcastCancelDetail, BroadcastDetail
from ..request_types import *

class AsyncBroadcasts:

    def __init__(self, http: AsyncHttpClient) -> None:
        ...

    async def lookup(self, broadcast_id: str) -> BroadcastDetail:
        ...

    async def cancel(self, broadcast_id: str) -> BroadcastCancelDetail:
        ...
