# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Generated public typing surface. Do not edit by hand."""
from typing import Any
from ..async_http_client import AsyncHttpClient
from .._models import BroadcastCreationDetail, Chime, ChimePage, ScheduleCreationDetail
from ..request_types import *

class AsyncChimes:

    def __init__(self, http: AsyncHttpClient) -> None:
        ...

    async def send(self, payload: SendChimeRequest) -> Chime:
        ...

    async def lookup(self, chime_id: str) -> Chime:
        ...

    async def page(self, payload: PageChimesRequest | None=None) -> ChimePage:
        ...

    async def schedule(self, payload: ScheduleChimeRequest) -> ScheduleCreationDetail:
        ...

    async def broadcast(self, payload: BroadcastRequest) -> BroadcastCreationDetail:
        ...
