# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Customers resource for creating and managing customer records."""
from __future__ import annotations
from ..async_http_client import AsyncHttpClient

class AsyncCustomers:
    """Customers resource for creating, updating, looking up, and paging customers."""

    def __init__(self, http: AsyncHttpClient):
        self.http = http

    async def create(self, payload: dict):
        """Create a customer record."""
        return await self.http.post('/customers/create', payload)

    async def lookup(self, customer_id: str):
        """Lookup a customer by ID."""
        return await self.http.post('/customers/lookup', {'customer_id': customer_id})

    async def update(self, payload: dict, idempotency_key: str | None=None):
        """Update supplied fields on a customer record."""
        headers = {'Idempotency-Key': idempotency_key} if idempotency_key else {}
        return await self.http.post_with_headers('/customers/update', payload, headers)

    async def page(self, payload: dict | None=None):
        """Page through customers."""
        return await self.http.post('/customers/page', payload or {})
