# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Generated public typing surface. Do not edit by hand."""
from typing import Any
from ..async_http_client import AsyncHttpClient
from inttegro.customer.customer import Customer
from inttegro.customer.page import Page
from inttegro.customer.create_request import CreateRequest
from inttegro.customer.update_request import UpdateRequest
from inttegro.customer.page_request import PageRequest

class AsyncCustomers:

    def __init__(self, http: AsyncHttpClient) -> None:
        ...

    async def create(self, payload: CreateRequest) -> Customer:
        ...

    async def lookup(self, customer_id: str) -> Customer:
        ...

    async def update(self, payload: UpdateRequest, idempotency_key: str | None=None) -> Customer:
        ...

    async def page(self, payload: PageRequest | None=None) -> Page:
        ...
