# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Generated public typing surface. Do not edit by hand."""
from typing import Any
from ..async_http_client import AsyncHttpClient
from .._models import Customer, CustomerPage
from ..request_types import *

class AsyncCustomers:

    def __init__(self, http: AsyncHttpClient) -> None:
        ...

    async def create(self, payload: CreateCustomerRequest) -> Customer:
        ...

    async def lookup(self, customer_id: str) -> Customer:
        ...

    async def update(self, payload: UpdateCustomerRequest, idempotency_key: str | None=None) -> Customer:
        ...

    async def page(self, payload: PageCustomersRequest | None=None) -> CustomerPage:
        ...
