# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""File reference reconciliation resource."""
from __future__ import annotations
from ..async_http_client import AsyncHttpClient

class AsyncFileReferences:
    """Reconcile Inttegro resource file references."""

    def __init__(self, http: AsyncHttpClient):
        self.http = http

    async def reconcile(self, payload: dict):
        """Replace the live file references for a Inttegro resource."""
        return await self.http.post('/file_references/reconcile', payload)
