# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Generated public typing surface. Do not edit by hand."""
from typing import Any
from ..async_http_client import AsyncHttpClient
from .._models import File, FilePage
from ..request_types import *

class FileDownload:

    def __init__(self, data: bytes, headers: dict[str, str] | None=None) -> None:
        ...

    def save_to(self, path: str) -> None:
        ...

class AsyncFiles:

    def __init__(self, http: AsyncHttpClient) -> None:
        ...

    async def create(self, *, file: str, purpose: str, title: str | None=None, custom_data: dict[str, str] | None=None, idempotency_key: str | None=None) -> File:
        ...

    async def lookup(self, file_id: str) -> File:
        ...

    async def page(self, payload: PageFilesRequest | None=None) -> FilePage:
        ...

    async def contents(self, *, file_id: str, disposition: str='attachment') -> FileDownload:
        ...

    async def delete(self, file_id: str) -> File:
        ...
