# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Managed file operations and binary download helpers."""
from __future__ import annotations
from pathlib import Path
from inttegro.file.file import File
from inttegro.file.page import Page
from ..async_http_client import AsyncHttpClient
from inttegro.file.page_request import PageRequest

class FileDownload:
    """Binary file content and the response headers needed to save it safely.

    This local helper never performs an API request by itself.
    """
    data: bytes
    'Raw response bytes exactly as returned by the file content endpoint.'
    headers: dict[str, str]
    'Response headers normalized by the HTTP transport.'

    def __init__(self, data: bytes, headers: dict[str, str] | None=None) -> None:
        """Create a download value from response ``data`` and optional ``headers``."""
        self.data = data
        self.headers = headers or {}

    def save_to(self, path: str) -> None:
        """Write the downloaded bytes to ``path``.

        Args:
            path (str): Documented path value for this operation.

        Returns:
            ``None`` after the local operation completes.
        """
        Path(path).write_bytes(self.data)

class AsyncFiles:
    """Create, inspect, download, page, and delete managed file resources.

    Access this service as ``AsyncInttegroClient.files``. Methods use the client's shared transport and return the typed resource shapes documented below.
    """

    def __init__(self, http: AsyncHttpClient):
        """Bind file operations to the client's shared HTTP transport."""
        self.http = http

    async def create(self, *, file: str, purpose: str, title: str | None=None, custom_data: dict[str, str] | None=None, idempotency_key: str | None=None) -> File:
        """Upload ``file`` and create a managed file for the stated ``purpose``.

        ``custom_data`` contains merchant-defined string metadata. Reuse
        ``idempotency_key`` when retrying the same logical upload.
        """
        headers = {'Idempotency-Key': idempotency_key} if idempotency_key else {}
        return await self.http.post_multipart('/files/create', {'purpose': purpose, 'title': title, 'custom_data': custom_data}, {'file': file}, headers=headers)

    async def lookup(self, file_id: str) -> File:
        """Return the file identified by ``file_id``.

        API endpoint: ``/files/lookup``.

        Args:
            file_id (str): Unique identifier of the file.

        Returns:
            ``File`` decoded from the documented response shape.

        Raises:
            APIError: The API rejected the request or could not complete it.
            NetworkError: The request could not reach the Inttegro API.
            TimeoutError: The configured request deadline elapsed.
        """
        return await self.http.post('/files/lookup', {'file_id': file_id})

    async def page(self, payload: PageRequest | None=None) -> Page:
        """Return a page of files visible to the authenticated application.

        API endpoint: ``/files/page``.

        Args:
            payload (PageRequest | None): Typed request object or equivalent request mapping for this operation.

        Returns:
            ``Page`` decoded from the documented response shape.

        Raises:
            APIError: The API rejected the request or could not complete it.
            NetworkError: The request could not reach the Inttegro API.
            TimeoutError: The configured request deadline elapsed.
        """
        return await self.http.post('/files/page', payload or {})

    async def contents(self, *, file_id: str, disposition: str='attachment') -> FileDownload:
        """Download ``file_id`` with the requested content ``disposition``.

        API endpoint: ``/files/contents``.

        Args:
            file_id (str): Unique identifier of the file.
            disposition (str): Requested content disposition for the download response.

        Returns:
            ``FileDownload`` decoded from the documented response shape.

        Raises:
            APIError: The API rejected the request or could not complete it.
            NetworkError: The request could not reach the Inttegro API.
            TimeoutError: The configured request deadline elapsed.
        """
        (data, headers) = await self.http.post_binary_json('/files/contents', {'file_id': file_id, 'disposition': disposition})
        return FileDownload(data, headers)

    async def delete(self, file_id: str) -> File:
        """Delete ``file_id`` and return its final typed file state.

        API endpoint: ``/files/delete``.

        Args:
            file_id (str): Unique identifier of the file.

        Returns:
            ``File`` decoded from the documented response shape.

        Raises:
            APIError: The API rejected the request or could not complete it.
            NetworkError: The request could not reach the Inttegro API.
            TimeoutError: The configured request deadline elapsed.
        """
        return await self.http.post('/files/delete', {'file_id': file_id})
