# Generated by scripts/generate_async_resources.py; do not edit by hand.
from __future__ import annotations
from .._models import FileLink, FileLinkCreation, FileLinkPage
from ..async_http_client import AsyncHttpClient
from ..request_types import CreateFileLinkRequest, PageFileLinksRequest, RevokeFileLinkRequest
from .files import FileDownload

class AsyncFileLinks:

    def __init__(self, http: AsyncHttpClient):
        self.http = http

    async def create(self, payload: CreateFileLinkRequest, idempotency_key: str | None=None) -> FileLinkCreation:
        headers = {'Idempotency-Key': idempotency_key} if idempotency_key else {}
        return await self.http.post_with_headers('/file_links/create', payload, headers)

    async def lookup(self, id: str) -> FileLink:
        return await self.http.post('/file_links/lookup', {'id': id})

    async def page(self, payload: PageFileLinksRequest | None=None) -> FileLinkPage:
        return await self.http.post('/file_links/page', payload or {})

    async def revoke(self, payload: RevokeFileLinkRequest, idempotency_key: str | None=None) -> FileLink:
        headers = {'Idempotency-Key': idempotency_key} if idempotency_key else {}
        return await self.http.post_with_headers('/file_links/revoke', payload, headers)

    async def open(self, url: str, save_to: str | None=None) -> FileDownload:
        (data, headers) = await self.http.get_binary_public(url)
        download = FileDownload(data, headers)
        if save_to:
            download.save_to(save_to)
        return download
