# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Generated public typing surface. Do not edit by hand."""
from typing import Any
from ..async_http_client import AsyncHttpClient
from .._models import FileLink, FileLinkCreation, FileLinkPage
from ..request_types import *
from .files import FileDownload

class AsyncFileLinks:

    def __init__(self, http: AsyncHttpClient) -> None:
        ...

    async def create(self, payload: CreateFileLinkRequest, idempotency_key: str | None=None) -> FileLinkCreation:
        ...

    async def lookup(self, id: str) -> FileLink:
        ...

    async def page(self, payload: PageFileLinksRequest | None=None) -> FileLinkPage:
        ...

    async def revoke(self, payload: RevokeFileLinkRequest, idempotency_key: str | None=None) -> FileLink:
        ...

    async def open(self, url: str, save_to: str | None=None) -> FileDownload:
        ...
