# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Generated public typing surface. Do not edit by hand."""
from typing import Any
from ..async_http_client import AsyncHttpClient
from inttegro.file_reference.reconciliation import Reconciliation
from inttegro.file_reference.reconcile_request import ReconcileRequest

class AsyncFileReferences:

    def __init__(self, http: AsyncHttpClient) -> None:
        ...

    async def reconcile(self, payload: ReconcileRequest) -> Reconciliation:
        ...
