# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Generated public typing surface. Do not edit by hand."""
from typing import Any
from ..async_http_client import AsyncHttpClient
from inttegro.financial_account.financial_account import FinancialAccount
from inttegro.financial_account.page import Page
from inttegro.financial_account.id_request import IDRequest
from inttegro.financial_account.page_request import PageRequest
from inttegro.financial_account.update_request import UpdateRequest
from inttegro.financial_account.disable_request import DisableRequest
from inttegro.financial_account.create_request import CreateRequest

class AsyncFinancialAccounts:

    def __init__(self, http: AsyncHttpClient) -> None:
        ...

    async def create(self, payload: CreateRequest) -> FinancialAccount:
        ...

    async def lookup(self, account_id: str) -> FinancialAccount:
        ...

    async def connect(self, payload: CreateRequest) -> FinancialAccount:
        ...

    async def archive(self, payload: DisableRequest) -> FinancialAccount:
        ...

    async def page(self, payload: PageRequest | None=None) -> Page:
        ...

    async def verify(self, payload: IDRequest) -> FinancialAccount:
        ...

    async def update(self, payload: UpdateRequest) -> FinancialAccount:
        ...

    async def enable_push(self, account_id: str) -> FinancialAccount:
        ...

    async def disable_push(self, account_id: str, unset_as_payout_destination: bool | None=None) -> FinancialAccount:
        ...

    async def disconnect(self, account_id: str, unset_as_payout_destination: bool | None=None) -> FinancialAccount:
        ...

    async def reconnect(self, account_id: str) -> FinancialAccount:
        ...

    async def enable_pull(self, account_id: str) -> FinancialAccount:
        ...

    async def disable_pull(self, account_id: str) -> FinancialAccount:
        ...
