# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Generated public typing surface. Do not edit by hand."""
from typing import Any
from ..async_http_client import AsyncHttpClient
from .._models import FinancialAccount, FinancialAccountPage
from ..request_types import *

class AsyncFinancialAccounts:

    def __init__(self, http: AsyncHttpClient) -> None:
        ...

    async def create(self, payload: FinancialAccountCreateRequest) -> FinancialAccount:
        ...

    async def lookup(self, account_id: str) -> FinancialAccount:
        ...

    async def connect(self, payload: FinancialAccountCreateRequest) -> FinancialAccount:
        ...

    async def archive(self, payload: FinancialAccountDisableRequest) -> FinancialAccount:
        ...

    async def page(self, payload: FinancialAccountPageRequest | None=None) -> FinancialAccountPage:
        ...

    async def verify(self, payload: FinancialAccountIDRequest) -> FinancialAccount:
        ...

    async def update(self, payload: FinancialAccountUpdateRequest) -> FinancialAccount:
        ...

    async def enable_push(self, account_id: str) -> FinancialAccount:
        ...

    async def disable_push(self, account_id: str, unset_as_payout_destination: bool | None=None) -> FinancialAccount:
        ...

    async def disconnect(self, account_id: str, unset_as_payout_destination: bool | None=None) -> FinancialAccount:
        ...

    async def reconnect(self, account_id: str) -> FinancialAccount:
        ...

    async def enable_pull(self, account_id: str) -> FinancialAccount:
        ...

    async def disable_pull(self, account_id: str) -> FinancialAccount:
        ...
