# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Secret key management resource."""
from __future__ import annotations
from ..async_http_client import AsyncHttpClient

class AsyncKeys:
    """Secret key generation, lookup, update, revocation, and usage operations."""

    def __init__(self, http: AsyncHttpClient):
        self.http = http

    async def generate(self, payload: dict | None=None):
        """Generate a new active secret key. The token is returned only once."""
        return await self.http.post('/keys/generate', payload or {})

    async def page(self, payload: dict | None=None):
        """List safe secret key metadata."""
        return await self.http.post('/keys/page', payload or {})

    async def lookup(self, secret_key_id: str):
        """Retrieve safe metadata for a secret key by ID."""
        return await self.lookup_with_params({'secret_key_id': secret_key_id})

    async def lookup_with_params(self, payload: dict):
        """Retrieve safe metadata using any supported ID alias."""
        return await self.http.post('/keys/lookup', payload)

    async def update(self, payload: dict):
        """Update safe mutable metadata for a secret key."""
        return await self.http.post('/keys/update', payload)

    async def destroy(self, secret_key_id: str):
        """Revoke a secret key by ID."""
        return await self.destroy_with_params({'secret_key_id': secret_key_id})

    async def destroy_with_params(self, payload: dict):
        """Revoke a secret key using any supported ID alias."""
        return await self.http.post('/keys/destroy', payload)

    async def usage(self, payload: dict | str):
        """Retrieve successful session usage and attributable failed verification attempts."""
        if isinstance(payload, str):
            payload = {'secret_key_id': payload}
        return await self.http.post('/keys/usage', payload)
