# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Generated public typing surface. Do not edit by hand."""
from typing import Any
from ..async_http_client import AsyncHttpClient
from .._models import GeneratedSecretKey, SecretKey, SecretKeyPage, SecretKeyUsage
from ..request_types import *

class AsyncKeys:

    def __init__(self, http: AsyncHttpClient) -> None:
        ...

    async def generate(self, payload: GenerateSecretKeyRequest | None=None) -> GeneratedSecretKey:
        ...

    async def page(self, payload: PageSecretKeysRequest | None=None) -> SecretKeyPage:
        ...

    async def lookup(self, secret_key_id: str) -> SecretKey:
        ...

    async def lookup_with_params(self, payload: LookupSecretKeyRequest) -> SecretKey:
        ...

    async def update(self, payload: UpdateSecretKeyRequest) -> SecretKey:
        ...

    async def destroy(self, secret_key_id: str) -> SecretKey:
        ...

    async def destroy_with_params(self, payload: DestroySecretKeyRequest) -> SecretKey:
        ...

    async def usage(self, payload: SecretKeyUsageRequest | str) -> SecretKeyUsage:
        ...
