# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Secret key management resource."""
from __future__ import annotations
from ..async_http_client import AsyncHttpClient

class AsyncKeys:
    """Secret key generation, lookup, update, revocation, and usage operations.

    Access this service as ``AsyncInttegroClient.keys``. Methods use the client's shared transport and return the typed resource shapes documented below.
    """

    def __init__(self, http: AsyncHttpClient):
        self.http = http

    async def generate(self, payload: dict | None=None):
        """Generate a new active secret key. The token is returned only once.

        API endpoint: ``/keys/generate``.

        Args:
            payload (dict | None): Typed request object or equivalent request mapping for this operation.

        Returns:
            ``Generated`` decoded from the documented response shape.

        Raises:
            APIError: The API rejected the request or could not complete it.
            NetworkError: The request could not reach the Inttegro API.
            TimeoutError: The configured request deadline elapsed.
        """
        return await self.http.post('/keys/generate', payload or {})

    async def page(self, payload: dict | None=None):
        """List safe secret key metadata.

        API endpoint: ``/keys/page``.

        Args:
            payload (dict | None): Typed request object or equivalent request mapping for this operation.

        Returns:
            ``Page`` decoded from the documented response shape.

        Raises:
            APIError: The API rejected the request or could not complete it.
            NetworkError: The request could not reach the Inttegro API.
            TimeoutError: The configured request deadline elapsed.
        """
        return await self.http.post('/keys/page', payload or {})

    async def lookup(self, secret_key_id: str):
        """Retrieve safe metadata for a secret key by ID.

        Args:
            secret_key_id (str): Unique identifier of the secret key.

        Returns:
            ``SecretKey`` decoded from the documented response shape.
        """
        return await self.lookup_with_params({'secret_key_id': secret_key_id})

    async def lookup_with_params(self, payload: dict):
        """Retrieve safe metadata using any supported ID alias.

        API endpoint: ``/keys/lookup``.

        Args:
            payload (dict): Typed request object or equivalent request mapping for this operation.

        Returns:
            ``SecretKey`` decoded from the documented response shape.

        Raises:
            APIError: The API rejected the request or could not complete it.
            NetworkError: The request could not reach the Inttegro API.
            TimeoutError: The configured request deadline elapsed.
        """
        return await self.http.post('/keys/lookup', payload)

    async def update(self, payload: dict):
        """Update safe mutable metadata for a secret key.

        API endpoint: ``/keys/update``.

        Args:
            payload (dict): Typed request object or equivalent request mapping for this operation.

        Returns:
            ``SecretKey`` decoded from the documented response shape.

        Raises:
            APIError: The API rejected the request or could not complete it.
            NetworkError: The request could not reach the Inttegro API.
            TimeoutError: The configured request deadline elapsed.
        """
        return await self.http.post('/keys/update', payload)

    async def destroy(self, secret_key_id: str):
        """Revoke a secret key by ID.

        Args:
            secret_key_id (str): Unique identifier of the secret key.

        Returns:
            ``SecretKey`` decoded from the documented response shape.
        """
        return await self.destroy_with_params({'secret_key_id': secret_key_id})

    async def destroy_with_params(self, payload: dict):
        """Revoke a secret key using any supported ID alias.

        API endpoint: ``/keys/destroy``.

        Args:
            payload (dict): Typed request object or equivalent request mapping for this operation.

        Returns:
            ``SecretKey`` decoded from the documented response shape.

        Raises:
            APIError: The API rejected the request or could not complete it.
            NetworkError: The request could not reach the Inttegro API.
            TimeoutError: The configured request deadline elapsed.
        """
        return await self.http.post('/keys/destroy', payload)

    async def usage(self, payload: dict | str):
        """Retrieve successful session usage and attributable failed verification attempts.

        API endpoint: ``/keys/usage``.

        Args:
            payload (dict | str): Typed request object or equivalent request mapping for this operation.

        Returns:
            ``Usage`` decoded from the documented response shape.

        Raises:
            APIError: The API rejected the request or could not complete it.
            NetworkError: The request could not reach the Inttegro API.
            TimeoutError: The configured request deadline elapsed.
        """
        if isinstance(payload, str):
            payload = {'secret_key_id': payload}
        return await self.http.post('/keys/usage', payload)
