# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Generated public typing surface. Do not edit by hand."""
from typing import Any
from ..async_http_client import AsyncHttpClient
from .._models import MessageTemplate, MessageTemplatePreview, MessageTemplatesPage
from ..request_types import *

class AsyncMessageTemplates:

    def __init__(self, http: AsyncHttpClient) -> None:
        ...

    async def create(self, payload: CreateMessageTemplateRequest, idempotency_key: str | None=None) -> MessageTemplate:
        ...

    async def update(self, payload: UpdateMessageTemplateRequest, idempotency_key: str | None=None) -> MessageTemplate:
        ...

    async def publish(self, template_id: str, idempotency_key: str | None=None) -> MessageTemplate:
        ...

    async def archive(self, template_id: str, idempotency_key: str | None=None) -> MessageTemplate:
        ...

    async def lookup(self, template_id: str) -> MessageTemplate:
        ...

    async def page(self, payload: PageMessageTemplatesRequest | None=None) -> MessageTemplatesPage:
        ...

    async def render_preview(self, payload: RenderMessageTemplatePreviewRequest) -> MessageTemplatePreview:
        ...
