# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Message templates resource for reusable SMS and email content."""
from __future__ import annotations
from ..async_http_client import AsyncHttpClient

class AsyncMessageTemplates:
    """Create, publish, archive, look up, page, and preview message templates."""

    def __init__(self, http: AsyncHttpClient):
        self.http = http

    async def create(self, payload: dict, idempotency_key: str | None=None):
        """Create a reusable message template."""
        return await self.http.post_with_headers('/message_templates/create', payload, self._idempotency_headers(idempotency_key))

    async def update(self, payload: dict, idempotency_key: str | None=None):
        """Update a message template draft."""
        return await self.http.post_with_headers('/message_templates/update', payload, self._idempotency_headers(idempotency_key))

    async def publish(self, template_id: str, idempotency_key: str | None=None):
        """Publish the current draft version of a template."""
        return await self.http.post_with_headers('/message_templates/publish', {'id': template_id}, self._idempotency_headers(idempotency_key))

    async def archive(self, template_id: str, idempotency_key: str | None=None):
        """Archive a template."""
        return await self.http.post_with_headers('/message_templates/archive', {'id': template_id}, self._idempotency_headers(idempotency_key))

    async def lookup(self, template_id: str):
        """Look up one template by ID."""
        return await self.http.post('/message_templates/lookup', {'id': template_id})

    async def page(self, payload: dict | None=None):
        """Page through message templates."""
        return await self.http.post('/message_templates/page', payload or {})

    async def render_preview(self, payload: dict):
        """Render a draft-aware template preview."""
        return await self.http.post('/message_templates/render_preview', payload)

    def _idempotency_headers(self, idempotency_key: str | None) -> dict[str, str]:
        return {'Idempotency-Key': idempotency_key} if idempotency_key else {}
