# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Generated public typing surface. Do not edit by hand."""
from typing import Any
from ..async_http_client import AsyncHttpClient
from .._models import Order, OrderDocumentDeliveryResult, OrderPage
from ..request_types import *

class AsyncOrders:

    def __init__(self, http: AsyncHttpClient) -> None:
        ...

    async def create(self, payload: CreateOrderRequest) -> Order:
        ...

    async def lookup(self, order_id: str, **options: object) -> Order:
        ...

    async def update(self, payload: UpdateOrderRequest) -> Order:
        ...

    async def pay(self, payload: PayOrderRequest) -> Order:
        ...

    async def confirm_payment(self, payload: ConfirmPaymentRequest) -> Order:
        ...

    async def request_confirmation(self, order_id: str, request_meta: dict[str, str] | None=None) -> Order:
        ...

    async def finalize(self, order_id: str, request_meta: dict[str, str] | None=None) -> Order:
        ...

    async def send_invoice(self, payload: OrderDocumentDeliveryRequest) -> OrderDocumentDeliveryResult:
        ...

    async def send_receipt(self, payload: OrderDocumentDeliveryRequest) -> OrderDocumentDeliveryResult:
        ...

    async def complete(self, payload: CompleteOrderRequest) -> Order:
        ...

    async def cancel(self, order_id: str, request_meta: dict[str, str] | None=None) -> Order:
        ...

    async def page(self, payload: PageOrdersRequest | None=None) -> OrderPage:
        ...
