# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Generated public typing surface. Do not edit by hand."""
from typing import Any
from ..async_http_client import AsyncHttpClient
from .._models import OTPTransaction, OTPVerification
from ..request_types import *

class AsyncOtp:

    def __init__(self, http: AsyncHttpClient) -> None:
        ...

    async def initiate(self, payload: InitiateOTPRequest) -> OTPTransaction:
        ...

    async def verify(self, payload: VerifyOTPRequest) -> OTPVerification:
        ...

    async def lookup(self, payload: LookupOTPRequest) -> OTPTransaction:
        ...

    async def cancel(self, payload: LookupOTPRequest) -> OTPTransaction:
        ...
