# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Generated public typing surface. Do not edit by hand."""
from typing import Any
from ..async_http_client import AsyncHttpClient
from .._models import PaymentMethod, PaymentMethodDeletion, PaymentMethodPage, PaymentMethodSettings, PaymentMethodVerificationSession
from ..request_types import *

class AsyncPaymentMethods:

    def __init__(self, http: AsyncHttpClient) -> None:
        ...

    async def tokenize(self, payload: TokenizeMobileMoneyPaymentMethodRequest) -> PaymentMethod:
        ...

    async def verify(self, payment_method_id: str, request_meta: dict[str, str] | None=None) -> PaymentMethodVerificationSession:
        ...

    async def confirm_verification(self, payload: LookupPaymentMethodRequest) -> PaymentMethod:
        ...

    async def lookup(self, payment_method_id: str) -> PaymentMethod:
        ...

    async def page(self, payload: PaymentMethodPageRequest | None=None) -> PaymentMethodPage:
        ...

    async def update(self, payload: UpdatePaymentMethodRequest) -> PaymentMethod:
        ...

    async def activate(self, payment_method_id: str) -> PaymentMethod:
        ...

    async def disactivate(self, payment_method_id: str) -> PaymentMethod:
        ...

    async def deactivate(self, payment_method_id: str) -> PaymentMethod:
        ...

    async def archive(self, payment_method_id: str) -> PaymentMethod:
        ...

    async def unarchive(self, payment_method_id: str) -> PaymentMethod:
        ...

    async def delete(self, payment_method_id: str, request_meta: dict[str, str] | None=None) -> PaymentMethodDeletion:
        ...

    async def settings(self) -> PaymentMethodSettings:
        ...
