# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Generated public typing surface. Do not edit by hand."""
from typing import Any
from ..async_http_client import AsyncHttpClient
from inttegro.payment_method.payment_method import PaymentMethod
from inttegro.payment_method.deletion import Deletion
from inttegro.payment_method.page import Page
from inttegro.payment_method.settings import Settings
from inttegro.payment_method.verification_session import VerificationSession
from inttegro.payment_method.tokenize_mobile_money_request import TokenizeMobileMoneyRequest
from inttegro.payment_method.lookup_request import LookupRequest
from inttegro.payment_method.page_request import PageRequest
from inttegro.payment_method.update_request import UpdateRequest

class AsyncPaymentMethods:

    def __init__(self, http: AsyncHttpClient) -> None:
        ...

    async def tokenize(self, payload: TokenizeMobileMoneyRequest) -> PaymentMethod:
        ...

    async def verify(self, payment_method_id: str, request_meta: dict[str, str] | None=None) -> VerificationSession:
        ...

    async def confirm_verification(self, payload: LookupRequest) -> PaymentMethod:
        ...

    async def lookup(self, payment_method_id: str) -> PaymentMethod:
        ...

    async def page(self, payload: PageRequest | None=None) -> Page:
        ...

    async def update(self, payload: UpdateRequest) -> PaymentMethod:
        ...

    async def activate(self, payment_method_id: str) -> PaymentMethod:
        ...

    async def disactivate(self, payment_method_id: str) -> PaymentMethod:
        ...

    async def deactivate(self, payment_method_id: str) -> PaymentMethod:
        ...

    async def archive(self, payment_method_id: str) -> PaymentMethod:
        ...

    async def unarchive(self, payment_method_id: str) -> PaymentMethod:
        ...

    async def delete(self, payment_method_id: str, request_meta: dict[str, str] | None=None) -> Deletion:
        ...

    async def settings(self) -> Settings:
        ...
