# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Generated public typing surface. Do not edit by hand."""
from typing import Any
from ..async_http_client import AsyncHttpClient
from inttegro.payout.payout import Payout
from inttegro.payout.page import Page
from inttegro.payout.settings_lookup import SettingsLookup
from inttegro.payout.settings_mutation import SettingsMutation
from inttegro.schedule.payout_request import PayoutRequest
from inttegro.payout.set_destinations_request import SetDestinationsRequest
from inttegro.payout.page_request import PageRequest

class AsyncPayouts:

    def __init__(self, http: AsyncHttpClient) -> None:
        ...

    async def set_destinations(self, destinations: SetDestinationsRequest | dict[str, str]) -> SettingsMutation:
        ...

    async def settings(self) -> SettingsLookup:
        ...

    async def schedule(self, payload: PayoutRequest) -> Payout:
        ...

    async def lookup(self, payout_id: str) -> Payout:
        ...

    async def disable_automatic(self) -> SettingsMutation:
        ...

    async def enable_automatic(self) -> SettingsMutation:
        ...

    async def enable_fx(self) -> SettingsLookup:
        ...

    async def disable_fx(self) -> SettingsLookup:
        ...

    async def page(self, payload: PageRequest | None=None) -> Page:
        ...

    async def cancel(self, payout_id: str) -> Payout:
        ...
