# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Generated public typing surface. Do not edit by hand."""
from typing import Any
from ..async_http_client import AsyncHttpClient
from .._models import Payout, PayoutPage, PayoutSettingsLookup, PayoutSettingsMutation
from ..request_types import *

class AsyncPayouts:

    def __init__(self, http: AsyncHttpClient) -> None:
        ...

    async def set_destinations(self, destinations: SetPayoutDestinationsRequest | dict[str, str]) -> PayoutSettingsMutation:
        ...

    async def settings(self) -> PayoutSettingsLookup:
        ...

    async def schedule(self, payload: SchedulePayoutRequest) -> Payout:
        ...

    async def lookup(self, payout_id: str) -> Payout:
        ...

    async def disable_automatic(self) -> PayoutSettingsMutation:
        ...

    async def enable_automatic(self) -> PayoutSettingsMutation:
        ...

    async def enable_fx(self) -> PayoutSettingsLookup:
        ...

    async def disable_fx(self) -> PayoutSettingsLookup:
        ...

    async def page(self, payload: PagePayoutsRequest | None=None) -> PayoutPage:
        ...

    async def cancel(self, payout_id: str) -> Payout:
        ...
