# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Prices resource for managing catalog prices."""
from __future__ import annotations
from ..async_http_client import AsyncHttpClient

class AsyncPrices:
    """Prices resource for creating, updating, and managing prices."""

    def __init__(self, http: AsyncHttpClient):
        self.http = http

    async def create(self, payload: dict):
        """Create a price."""
        return await self.http.post('/prices/create', payload)

    async def lookup(self, price_id: str):
        """Lookup a price by ID."""
        return await self.http.post('/prices/lookup', {'price_id': price_id})

    async def page(self, payload: dict | None=None):
        """Page through prices."""
        return await self.http.post('/prices/page', payload or {})

    async def update(self, payload: dict):
        """Update a price."""
        return await self.http.post('/prices/update', payload)

    async def activate(self, price_id: str):
        """Activate an inactive price."""
        return await self.http.post('/prices/activate', {'price_id': price_id})

    async def deactivate(self, price_id: str):
        """Deactivate a price."""
        return await self.http.post('/prices/deactivate', {'price_id': price_id})

    async def archive(self, price_id: str, idempotency_key: str | None=None):
        """Archive a price and mark it inactive."""
        headers = {'Idempotency-Key': idempotency_key} if idempotency_key else {}
        return await self.http.post_with_headers('/prices/archive', {'price_id': price_id}, headers)
