# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Generated public typing surface. Do not edit by hand."""
from typing import Any
from ..async_http_client import AsyncHttpClient
from .._models import CatalogPrice, PricePage
from ..request_types import *

class AsyncPrices:

    def __init__(self, http: AsyncHttpClient) -> None:
        ...

    async def create(self, payload: CatalogPriceParams) -> CatalogPrice:
        ...

    async def lookup(self, price_id: str) -> CatalogPrice:
        ...

    async def page(self, payload: PricePageRequest | None=None) -> PricePage:
        ...

    async def update(self, payload: UpdatePriceRequest) -> CatalogPrice:
        ...

    async def activate(self, price_id: str) -> CatalogPrice:
        ...

    async def deactivate(self, price_id: str) -> CatalogPrice:
        ...

    async def archive(self, price_id: str, idempotency_key: str | None=None) -> CatalogPrice:
        ...
