# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Generated public typing surface. Do not edit by hand."""
from typing import Any
from ..async_http_client import AsyncHttpClient
from .._models import CatalogPrice, Product, ProductPage
from ..request_types import *

class AsyncProducts:

    def __init__(self, http: AsyncHttpClient) -> None:
        ...

    async def create(self, payload: CreateProductRequest) -> Product:
        ...

    async def add_price(self, payload: AddProductPriceRequest) -> CatalogPrice:
        ...

    async def set_default_unit_price(self, payload: LookupProductRequest) -> Product:
        ...

    async def lookup(self, product_id: str) -> Product:
        ...

    async def update(self, payload: UpdateProductRequest) -> Product:
        ...

    async def publish(self, product_id: str) -> Product:
        ...

    async def unpublish(self, product_id: str) -> Product:
        ...

    async def archive(self, product_id: str) -> Product:
        ...

    async def page(self, payload: PageProductsRequest | None=None) -> ProductPage:
        ...
