# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Products resource for managing catalog products."""
from __future__ import annotations
from ..async_http_client import AsyncHttpClient

class AsyncProducts:
    """Products resource for creating, updating, and managing products."""

    def __init__(self, http: AsyncHttpClient):
        self.http = http

    async def create(self, payload: dict):
        """Create a product."""
        return await self.http.post('/products/create', payload)

    async def add_price(self, payload: dict):
        """Add a price to a product."""
        return await self.http.post('/products/add_price', payload)

    async def set_default_unit_price(self, payload: dict):
        """Set a product's default unit price."""
        return await self.http.post('/products/set_default_unit_price', payload)

    async def lookup(self, product_id: str):
        """Lookup a product by ID."""
        return await self.http.post('/products/lookup', {'product_id': product_id})

    async def update(self, payload: dict):
        """Update a product."""
        return await self.http.post('/products/update', payload)

    async def publish(self, product_id: str):
        """Publish a product."""
        return await self.http.post('/products/publish', {'product_id': product_id})

    async def unpublish(self, product_id: str):
        """Unpublish a product."""
        return await self.http.post('/products/unpublish', {'product_id': product_id})

    async def archive(self, product_id: str):
        """Archive a product."""
        return await self.http.post('/products/archive', {'product_id': product_id})

    async def page(self, payload: dict | None=None):
        """Page through products."""
        return await self.http.post('/products/page', payload or {})
