# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Generated public typing surface. Do not edit by hand."""
from typing import Any
from ..async_http_client import AsyncHttpClient
from .._models import PurchaseIntent, PurchaseIntentPage
from ..request_types import *

class AsyncPurchaseIntents:

    def __init__(self, http: AsyncHttpClient) -> None:
        ...

    async def create(self, payload: CreatePurchaseIntentRequest) -> PurchaseIntent:
        ...

    async def update(self, payload: UpdatePurchaseIntentRequest) -> PurchaseIntent:
        ...

    async def cancel(self, id: str) -> PurchaseIntent:
        ...

    async def lookup(self, id: str) -> PurchaseIntent:
        ...

    async def page(self, payload: PagePurchaseIntentsRequest) -> PurchaseIntentPage:
        ...
