# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Generated public typing surface. Do not edit by hand."""
from typing import Any
from ..async_http_client import AsyncHttpClient
from inttegro.purchase_intent.purchase_intent import PurchaseIntent
from inttegro.purchase_intent.page import Page
from inttegro.purchase_intent.create_request import CreateRequest
from inttegro.purchase_intent.update_request import UpdateRequest
from inttegro.purchase_intent.page_request import PageRequest

class AsyncPurchaseIntents:

    def __init__(self, http: AsyncHttpClient) -> None:
        ...

    async def create(self, payload: CreateRequest) -> PurchaseIntent:
        ...

    async def update(self, payload: UpdateRequest) -> PurchaseIntent:
        ...

    async def cancel(self, id: str) -> PurchaseIntent:
        ...

    async def lookup(self, id: str) -> PurchaseIntent:
        ...

    async def page(self, payload: PageRequest) -> Page:
        ...
