# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Purchase intent resource for Pages Buy links."""
from __future__ import annotations
from ..async_http_client import AsyncHttpClient

class AsyncPurchaseIntents:
    """Create, update, cancel, look up, and page Buy link purchase intents."""

    def __init__(self, http: AsyncHttpClient):
        self.http = http

    async def create(self, payload: dict):
        """Create a Buy link purchase intent."""
        return await self.http.post('/purchase_intents/create', payload)

    async def update(self, payload: dict):
        """Update mutable Buy link purchase intent fields."""
        return await self.http.post('/purchase_intents/update', payload)

    async def cancel(self, id: str):
        """Cancel a Buy link purchase intent."""
        return await self.http.post('/purchase_intents/cancel', {'id': id})

    async def lookup(self, id: str):
        """Retrieve a Buy link purchase intent by ID."""
        return await self.http.post('/purchase_intents/lookup', {'id': id})

    async def page(self, payload: dict):
        """List Buy link purchase intents."""
        return await self.http.post('/purchase_intents/page', payload)
