# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Generated public typing surface. Do not edit by hand."""
from typing import Any
from ..async_http_client import AsyncHttpClient
from .._models import Refund, RefundPage
from ..request_types import *

class AsyncRefunds:

    def __init__(self, http: AsyncHttpClient) -> None:
        ...

    async def create(self, payload: CreateRefundRequest, idempotency_key: str | None=None) -> Refund:
        ...

    async def cancel(self, refund_id: str, idempotency_key: str | None=None) -> Refund:
        ...

    async def lookup(self, refund_id: str) -> Refund:
        ...

    async def page(self, payload: PageRefundsRequest) -> RefundPage:
        ...
