# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Refunds resource for managing order refunds."""
from __future__ import annotations
from .._models import Refund, RefundPage
from ..async_http_client import AsyncHttpClient
from ..request_types import CreateRefundRequest, PageRefundsRequest

class AsyncRefunds:
    """Create, cancel, look up, and page through refunds."""

    def __init__(self, http: AsyncHttpClient):
        self.http = http

    async def create(self, payload: CreateRefundRequest, idempotency_key: str | None=None) -> Refund:
        """Create a refund for paid order line items."""
        return await self.http.post_with_headers('/refunds/create', payload, self._idempotency_headers(idempotency_key))

    async def cancel(self, refund_id: str, idempotency_key: str | None=None) -> Refund:
        """Cancel a pending refund."""
        return await self.http.post_with_headers('/refunds/cancel', {'refund_id': refund_id}, self._idempotency_headers(idempotency_key))

    async def lookup(self, refund_id: str) -> Refund:
        """Look up a refund by ID."""
        return await self.http.post('/refunds/lookup', {'refund_id': refund_id})

    async def page(self, payload: PageRefundsRequest) -> RefundPage:
        """Page through refunds."""
        return await self.http.post('/refunds/page', payload)

    def _idempotency_headers(self, idempotency_key: str | None) -> dict[str, str]:
        return {'Idempotency-Key': idempotency_key} if idempotency_key else {}
