# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Refunds resource for managing order refunds."""
from __future__ import annotations
from inttegro.refund.refund import Refund
from inttegro.refund.page import Page
from ..async_http_client import AsyncHttpClient
from inttegro.refund.create_request import CreateRequest
from inttegro.refund.page_request import PageRequest

class AsyncRefunds:
    """Create, cancel, look up, and page through refunds.

    Access this service as ``AsyncInttegroClient.refunds``. Methods use the client's shared transport and return the typed resource shapes documented below.
    """

    def __init__(self, http: AsyncHttpClient):
        self.http = http

    async def create(self, payload: CreateRequest, idempotency_key: str | None=None) -> Refund:
        """Create a refund for paid order line items.

        API endpoint: ``/refunds/create``.

        Args:
            payload (CreateRequest): Typed request object or equivalent request mapping for this operation.
            idempotency_key (str | None): Optional stable key to reuse when retrying the same logical write.

        Returns:
            ``Refund`` decoded from the documented response shape.

        Raises:
            APIError: The API rejected the request or could not complete it.
            NetworkError: The request could not reach the Inttegro API.
            TimeoutError: The configured request deadline elapsed.
        """
        return await self.http.post_with_headers('/refunds/create', payload, self._idempotency_headers(idempotency_key))

    async def cancel(self, refund_id: str, idempotency_key: str | None=None) -> Refund:
        """Cancel a pending refund.

        API endpoint: ``/refunds/cancel``.

        Args:
            refund_id (str): Unique identifier of the refund.
            idempotency_key (str | None): Optional stable key to reuse when retrying the same logical write.

        Returns:
            ``Refund`` decoded from the documented response shape.

        Raises:
            APIError: The API rejected the request or could not complete it.
            NetworkError: The request could not reach the Inttegro API.
            TimeoutError: The configured request deadline elapsed.
        """
        return await self.http.post_with_headers('/refunds/cancel', {'refund_id': refund_id}, self._idempotency_headers(idempotency_key))

    async def lookup(self, refund_id: str) -> Refund:
        """Look up a refund by ID.

        API endpoint: ``/refunds/lookup``.

        Args:
            refund_id (str): Unique identifier of the refund.

        Returns:
            ``Refund`` decoded from the documented response shape.

        Raises:
            APIError: The API rejected the request or could not complete it.
            NetworkError: The request could not reach the Inttegro API.
            TimeoutError: The configured request deadline elapsed.
        """
        return await self.http.post('/refunds/lookup', {'refund_id': refund_id})

    async def page(self, payload: PageRequest) -> Page:
        """Page through refunds.

        API endpoint: ``/refunds/page``.

        Args:
            payload (PageRequest): Typed request object or equivalent request mapping for this operation.

        Returns:
            ``Page`` decoded from the documented response shape.

        Raises:
            APIError: The API rejected the request or could not complete it.
            NetworkError: The request could not reach the Inttegro API.
            TimeoutError: The configured request deadline elapsed.
        """
        return await self.http.post('/refunds/page', payload)

    def _idempotency_headers(self, idempotency_key: str | None) -> dict[str, str]:
        return {'Idempotency-Key': idempotency_key} if idempotency_key else {}
