# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Schedules resource for looking up and canceling scheduled chimes."""
from __future__ import annotations
from ..async_http_client import AsyncHttpClient

class AsyncSchedules:
    """Schedules resource for managing scheduled chimes."""

    def __init__(self, http: AsyncHttpClient):
        self.http = http

    async def lookup(self, schedule_id: str):
        """Lookup a scheduled chime by schedule ID."""
        return await self.http.post('/schedules/lookup', {'schedule_id': schedule_id})

    async def cancel(self, schedule_id: str):
        """Cancel a scheduled chime by schedule ID."""
        return await self.http.post('/schedules/cancel', {'schedule_id': schedule_id})
