# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Generated public typing surface. Do not edit by hand."""
from typing import Any
from ..async_http_client import AsyncHttpClient
from inttegro.shared.country_specification import CountrySpecification

class AsyncSpec:

    def __init__(self, http: AsyncHttpClient) -> None:
        ...

    async def countries(self) -> dict[str, CountrySpecification]:
        ...
