# Generated by scripts/generate_async_resources.py; do not edit by hand.
from __future__ import annotations
from .._models import UploadFulfillment, UploadRequest, UploadRequestPage
from ..async_http_client import AsyncHttpClient
from ..request_types import CancelUploadRequestRequest, CreateUploadRequestRequest, PageUploadRequestsRequest, ReviewUploadRequestAttemptByIDRequest, ReviewUploadRequestAttemptByOrdinalRequest

class AsyncUploadRequests:

    def __init__(self, http: AsyncHttpClient):
        self.http = http

    async def create(self, payload: CreateUploadRequestRequest, idempotency_key: str | None=None) -> UploadRequest:
        headers = {'Idempotency-Key': idempotency_key} if idempotency_key else {}
        return await self.http.post_with_headers('/upload_requests/create', payload, headers)

    async def lookup(self, id: str) -> UploadRequest:
        return await self.http.post('/upload_requests/lookup', {'id': id})

    async def page(self, payload: PageUploadRequestsRequest | None=None) -> UploadRequestPage:
        return await self.http.post('/upload_requests/page', payload or {})

    async def cancel(self, payload: CancelUploadRequestRequest, idempotency_key: str | None=None) -> UploadRequest:
        headers = {'Idempotency-Key': idempotency_key} if idempotency_key else {}
        return await self.http.post_with_headers('/upload_requests/cancel', payload, headers)

    async def review(self, payload: ReviewUploadRequestAttemptByIDRequest | ReviewUploadRequestAttemptByOrdinalRequest, idempotency_key: str | None=None) -> UploadRequest:
        headers = {'Idempotency-Key': idempotency_key} if idempotency_key else {}
        return await self.http.post_with_headers('/upload_requests/review', payload, headers)

    async def fulfill(self, *, upload_url: str, file: str) -> UploadFulfillment:
        return await self.http.post_multipart(upload_url, {}, {'file': file}, authenticated=False, operation='upload_requests.upload')
