# Generated by scripts/generate_async_resources.py; do not edit by hand.
"""Generated public typing surface. Do not edit by hand."""
from typing import Any
from ..async_http_client import AsyncHttpClient
from .._models import UploadFulfillment, UploadRequest, UploadRequestPage
from ..request_types import *

class AsyncUploadRequests:

    def __init__(self, http: AsyncHttpClient) -> None:
        ...

    async def create(self, payload: CreateUploadRequestRequest, idempotency_key: str | None=None) -> UploadRequest:
        ...

    async def lookup(self, id: str) -> UploadRequest:
        ...

    async def page(self, payload: PageUploadRequestsRequest | None=None) -> UploadRequestPage:
        ...

    async def cancel(self, payload: CancelUploadRequestRequest, idempotency_key: str | None=None) -> UploadRequest:
        ...

    async def review(self, payload: ReviewUploadRequestAttemptByIDRequest | ReviewUploadRequestAttemptByOrdinalRequest, idempotency_key: str | None=None) -> UploadRequest:
        ...

    async def fulfill(self, *, upload_url: str, file: str) -> UploadFulfillment:
        ...
