"""Official Python client for the Inttegro API.

Domain types live in singular resource namespaces. For example, import
``inttegro.payment.Payment`` or ``inttegro.product.Type`` instead of relying on
a flat package-level model namespace.
"""

from .async_client import AsyncInttegroClient
from .async_http_client import AsyncHTTPClient
from .client import InttegroClient
from .error_reporting import (
    APIErrorReportContext,
    ErrorReport,
    ErrorReporter,
    ErrorReportingPolicy,
    HTTPReportContext,
    SDKReportContext,
    TraceReportContext,
)
from .errors import (
    APIError,
    AuthenticationError,
    InttegroError,
    NetworkError,
    RateLimitError,
    TimeoutError,
)
from . import (
    app,
    balance,
    balance_transaction,
    bank_account,
    broadcast,
    checkout,
    chime,
    customer,
    file,
    file_link,
    file_reference,
    financial_account,
    message_template,
    money,
    order,
    otp,
    payment,
    payment_method,
    payout,
    price,
    product,
    purchase_intent,
    refund,
    schedule,
    secret_key,
    shared,
    upload_request,
    wallet,
)

__all__ = [
    "APIError",
    "APIErrorReportContext",
    "AsyncHTTPClient",
    "AsyncInttegroClient",
    "AuthenticationError",
    "ErrorReport",
    "ErrorReporter",
    "ErrorReportingPolicy",
    "HTTPReportContext",
    "InttegroClient",
    "InttegroError",
    "NetworkError",
    "RateLimitError",
    "SDKReportContext",
    "TimeoutError",
    "TraceReportContext",
    "app",
    "balance",
    "balance_transaction",
    "bank_account",
    "broadcast",
    "checkout",
    "chime",
    "customer",
    "file",
    "file_link",
    "file_reference",
    "financial_account",
    "message_template",
    "money",
    "order",
    "otp",
    "payment",
    "payment_method",
    "payout",
    "price",
    "product",
    "purchase_intent",
    "refund",
    "schedule",
    "secret_key",
    "shared",
    "upload_request",
    "wallet",
]
