"""Chime, broadcast, and schedule domain objects."""

from ._models import (
    BroadcastCancelDetail as CanceledBroadcast,
    BroadcastCreationDetail as CreatedBroadcast,
    BroadcastDetail as Broadcast,
    BroadcastError,
    Chime,
    ChimeEmailEvent as EmailEvent,
    ChimeEmailMessage as EmailContent,
    ChimePage as Page,
    ChimeTransmission as Transmission,
    ScheduleCancelDetail as CanceledSchedule,
    ScheduleCreationDetail as ScheduledChime,
    ScheduleDetail as Schedule,
    ScheduleError,
)

from .request_types import (
    BroadcastRequest,
    BroadcastRequestRequestMeta as BroadcastRequestMeta,
    ChimeEmailMailboxInput as EmailMailbox,
    ChimeEmailMessageInput as EmailMessage,
    ChimeInlineRecipientInputVariant1 as PhoneRecipient,
    ChimeInlineRecipientInputVariant1Phone as Phone,
    ChimeInlineRecipientInputVariant2 as EmailRecipient,
    ChimeInlineRecipientInputVariant2Email as Email,
    ChimeSavedCustomerRecipientInput as SavedCustomerRecipient,
    MessageTemplateReferenceInput as TemplateReference,
    PageChimesRequest as PageRequest,
    ScheduleChimeRequest as ScheduleRequest,
    ScheduleChimeRequestRequestMeta as ScheduleRequestMeta,
    SendChimeRequest as SendRequest,
    SendChimeRequestRequestMeta as SendRequestMeta,
)

__all__ = [
    "Broadcast",
    "BroadcastError",
    "BroadcastRequest",
    "BroadcastRequestMeta",
    "CanceledBroadcast",
    "CanceledSchedule",
    "Chime",
    "CreatedBroadcast",
    "Email",
    "EmailContent",
    "EmailEvent",
    "EmailMailbox",
    "EmailMessage",
    "EmailRecipient",
    "PageRequest",
    "Page",
    "Phone",
    "PhoneRecipient",
    "SavedCustomerRecipient",
    "Schedule",
    "ScheduleError",
    "ScheduleRequest",
    "ScheduleRequestMeta",
    "ScheduledChime",
    "SendRequest",
    "SendRequestMeta",
    "TemplateReference",
    "Transmission",
]
