"""Typed request objects for order operations."""

from .request_types import (
    AddressInput as Address,
    BillingDetailsInput as BillingDetails,
    CatalogProductWithPriceDataInput as CatalogProduct,
    CatalogProductWithPriceReferenceInput as CatalogProductReference,
    CompleteOrderRequest as CompleteRequest,
    ConfirmPaymentRequest,
    CreateOrderExistingCustomerInput as CreateForCustomerRequest,
    CreateOrderNewCustomerInput as CreateRequest,
    CreateOrderNewCustomerInputCheckoutSettings as CheckoutSettings,
    CreateOrderNewCustomerInputRequestMeta as RequestMeta,
    CustomerDataInput as Customer,
    FeeDetailsInput as Fee,
    FeeLineItemInput as FeeLineItem,
    InlineProductDetailsInput as Product,
    InvoiceSettingsInput as InvoiceSettings,
    MoneyInput as Money,
    OrderDocumentDeliveryRequest as DocumentDeliveryRequest,
    OrderPayoutSettingsRequest as PayoutSettings,
    OrderPayoutSettingsRequestDestination as PayoutDestination,
    PageOrdersRequest as PageRequest,
    PayOrderRequest as PayRequest,
    PaymentMethodDataInput as PaymentMethod,
    PaymentMethodDataInputMobileMoney as MobileMoney,
    ProductLineItemInput as ProductLineItem,
    ShippingDetailsInput as ShippingDetails,
    ShippingInput as Shipping,
    ShippingLineItemInput as ShippingLineItem,
    UpdateOrderRequest as UpdateRequest,
)

__all__ = [
    "Address",
    "BillingDetails",
    "CatalogProduct",
    "CatalogProductReference",
    "CheckoutSettings",
    "CompleteRequest",
    "ConfirmPaymentRequest",
    "CreateForCustomerRequest",
    "CreateRequest",
    "Customer",
    "DocumentDeliveryRequest",
    "Fee",
    "FeeLineItem",
    "InvoiceSettings",
    "MobileMoney",
    "Money",
    "PageRequest",
    "PayRequest",
    "PaymentMethod",
    "PayoutDestination",
    "PayoutSettings",
    "Product",
    "ProductLineItem",
    "RequestMeta",
    "ShippingDetails",
    "Shipping",
    "ShippingLineItem",
    "UpdateRequest",
]
