#!/usr/bin/env python3
"""Generate async resource classes from the synchronous SDK surface."""

from __future__ import annotations

import argparse
import ast
import difflib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "inttegro" / "resources"
TARGET = ROOT / "src" / "inttegro" / "async_resources"
HEADER = "# Generated by scripts/generate_async_resources.py; do not edit by hand.\n"


def is_self_attribute(call: ast.Call, owner: str, names: set[str] | None = None) -> bool:
    func = call.func
    if not isinstance(func, ast.Attribute):
        return False
    value = func.value
    if owner == "http":
        matches = isinstance(value, ast.Attribute) and isinstance(value.value, ast.Name) and value.value.id == "self" and value.attr == "http"
    else:
        matches = isinstance(value, ast.Name) and value.id == "self"
    return matches and (names is None or func.attr in names)


def resource_class_names(tree: ast.Module) -> set[str]:
    names: set[str] = set()
    for node in tree.body:
        if not isinstance(node, ast.ClassDef):
            continue
        if any(
            isinstance(child, ast.Assign)
            and any(isinstance(target, ast.Attribute) and target.attr == "http" for target in child.targets)
            for child in ast.walk(node)
        ):
            names.add(node.name)
    return names


def async_method_names(class_node: ast.ClassDef) -> set[str]:
    methods = {node.name: node for node in class_node.body if isinstance(node, ast.FunctionDef)}
    async_names = {
        name
        for name, node in methods.items()
        if any(isinstance(child, ast.Call) and is_self_attribute(child, "http") for child in ast.walk(node))
    }
    while True:
        expanded = async_names | {
            name
            for name, node in methods.items()
            if any(
                isinstance(child, ast.Call) and is_self_attribute(child, "self", async_names)
                for child in ast.walk(node)
            )
        }
        if expanded == async_names:
            return expanded
        async_names = expanded


class AsyncTransformer(ast.NodeTransformer):
    def __init__(self, resource_names: set[str]) -> None:
        self.resource_names = resource_names
        self.current_async_methods: set[str] = set()

    def visit_ImportFrom(self, node: ast.ImportFrom) -> ast.AST:
        if node.module == "http_client" and node.level == 2:
            node.module = "async_http_client"
            for alias in node.names:
                if alias.name == "HttpClient":
                    alias.name = "AsyncHttpClient"
        return node

    def visit_Name(self, node: ast.Name) -> ast.AST:
        if node.id == "HttpClient":
            node.id = "AsyncHttpClient"
        return node

    def visit_ClassDef(self, node: ast.ClassDef) -> ast.AST:
        previous = self.current_async_methods
        if node.name in self.resource_names:
            self.current_async_methods = async_method_names(node)
            node.name = f"Async{node.name}"
        self.generic_visit(node)
        self.current_async_methods = previous
        return node

    def visit_FunctionDef(self, node: ast.FunctionDef) -> ast.AST:
        if node.name not in self.current_async_methods:
            return self.generic_visit(node)
        transformed = self.generic_visit(node)
        assert isinstance(transformed, ast.FunctionDef)
        return ast.copy_location(
            ast.AsyncFunctionDef(
                name=transformed.name,
                args=transformed.args,
                body=transformed.body,
                decorator_list=transformed.decorator_list,
                returns=transformed.returns,
                type_comment=transformed.type_comment,
            ),
            node,
        )

    def visit_Call(self, node: ast.Call) -> ast.AST:
        transformed = self.generic_visit(node)
        assert isinstance(transformed, ast.Call)
        if is_self_attribute(transformed, "http") or is_self_attribute(transformed, "self", self.current_async_methods):
            return ast.copy_location(ast.Await(value=transformed), node)
        return transformed


class AsyncStubTransformer(ast.NodeTransformer):
    def __init__(self, resource_methods: dict[str, set[str]]) -> None:
        self.resource_methods = resource_methods
        self.current_async_methods: set[str] = set()

    def visit_ImportFrom(self, node: ast.ImportFrom) -> ast.AST:
        if node.module == "http_client" and node.level == 2:
            node.module = "async_http_client"
            for alias in node.names:
                if alias.name == "HttpClient":
                    alias.name = "AsyncHttpClient"
        return node

    def visit_Name(self, node: ast.Name) -> ast.AST:
        if node.id == "HttpClient":
            node.id = "AsyncHttpClient"
        return node

    def visit_ClassDef(self, node: ast.ClassDef) -> ast.AST:
        previous = self.current_async_methods
        methods = self.resource_methods.get(node.name)
        if methods is not None:
            self.current_async_methods = methods
            node.name = f"Async{node.name}"
        self.generic_visit(node)
        self.current_async_methods = previous
        return node

    def visit_FunctionDef(self, node: ast.FunctionDef) -> ast.AST:
        transformed = self.generic_visit(node)
        assert isinstance(transformed, ast.FunctionDef)
        if node.name not in self.current_async_methods:
            return transformed
        return ast.copy_location(
            ast.AsyncFunctionDef(
                name=transformed.name,
                args=transformed.args,
                body=transformed.body,
                decorator_list=transformed.decorator_list,
                returns=transformed.returns,
                type_comment=transformed.type_comment,
            ),
            node,
        )


def render(source_path: Path) -> str:
    tree = ast.parse(source_path.read_text(encoding="utf-8"))
    transformed = AsyncTransformer(resource_class_names(tree)).visit(tree)
    ast.fix_missing_locations(transformed)
    return HEADER + ast.unparse(transformed) + "\n"


def render_stub(stub_path: Path, source_path: Path) -> str:
    source_tree = ast.parse(source_path.read_text(encoding="utf-8"))
    methods = {
        node.name: async_method_names(node)
        for node in source_tree.body
        if isinstance(node, ast.ClassDef) and node.name in resource_class_names(source_tree)
    }
    stub_tree = ast.parse(stub_path.read_text(encoding="utf-8"))
    transformed = AsyncStubTransformer(methods).visit(stub_tree)
    ast.fix_missing_locations(transformed)
    return HEADER + ast.unparse(transformed) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when generated files are stale")
    args = parser.parse_args()
    expected = {path.name: render(path) for path in SOURCE.glob("*.py") if path.name != "__init__.py"}
    expected.update(
        {
            path.name: render_stub(path, SOURCE / f"{path.stem}.py")
            for path in SOURCE.glob("*.pyi")
            if (SOURCE / f"{path.stem}.py").exists()
        }
    )
    expected["__init__.py"] = HEADER

    if args.check:
        failures = []
        for name, content in sorted(expected.items()):
            path = TARGET / name
            actual = path.read_text(encoding="utf-8") if path.exists() else ""
            if actual != content:
                failures.extend(difflib.unified_diff(actual.splitlines(), content.splitlines(), fromfile=str(path), tofile=f"generated/{name}", lineterm=""))
        extras = sorted(
            path.name
            for pattern in ("*.py", "*.pyi")
            for path in TARGET.glob(pattern)
            if path.name not in expected
        )
        if failures or extras:
            print("\n".join(failures))
            if extras:
                print("Unexpected generated files: " + ", ".join(extras))
            return 1
        return 0

    TARGET.mkdir(parents=True, exist_ok=True)
    for pattern in ("*.py", "*.pyi"):
        for path in TARGET.glob(pattern):
            if path.name not in expected:
                path.unlink()
    for name, content in expected.items():
        (TARGET / name).write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
