"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from .._models import Application
from ..request_types import *

class Apps:
    def __init__(self, http: HttpClient) -> None: ...
    def create(self, payload: CreateApplicationRequest) -> Application: ...
    def lookup(self) -> Application: ...
    def update(self, payload: UpdateApplicationRequest) -> Application: ...
