"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from .._models import *
from ..request_types import *
from ..response_object import ResponseObject

class Chimes:
    def __init__(self, http: HttpClient) -> None: ...
    def send(self, payload: SendChimeRequest) -> ChimeResponse: ...
    def lookup(self, chime_id: str) -> ChimeResponse: ...
    def page(self, payload: PageChimesRequest | None = None) -> PageChimesResponse: ...
    def schedule(self, payload: ScheduleChimeRequest) -> ScheduleResponse: ...
    def broadcast(self, payload: BroadcastRequest) -> BroadcastResponse: ...
