"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from .._models import BroadcastCreationDetail, Chime, ChimePage, ScheduleCreationDetail
from ..request_types import *

class Chimes:
    def __init__(self, http: HttpClient) -> None: ...
    def send(self, payload: SendChimeRequest) -> Chime: ...
    def lookup(self, chime_id: str) -> Chime: ...
    def page(self, payload: PageChimesRequest | None = None) -> ChimePage: ...
    def schedule(self, payload: ScheduleChimeRequest) -> ScheduleCreationDetail: ...
    def broadcast(self, payload: BroadcastRequest) -> BroadcastCreationDetail: ...
