"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from .._models import *
from ..request_types import *
from ..response_object import ResponseObject

class Customers:
    def __init__(self, http: HttpClient) -> None: ...
    def create(self, payload: CreateCustomerRequest) -> CustomerResponse: ...
    def lookup(self, customer_id: str) -> CustomerResponse: ...
    def update(self, payload: UpdateCustomerRequest, idempotency_key: str | None = None) -> CustomerResponse: ...
    def page(self, payload: PageCustomersRequest | None = None) -> PageCustomersResponse: ...
