"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from .._models import Customer, CustomerPage
from ..request_types import *

class Customers:
    def __init__(self, http: HttpClient) -> None: ...
    def create(self, payload: CreateCustomerRequest) -> Customer: ...
    def lookup(self, customer_id: str) -> Customer: ...
    def update(self, payload: UpdateCustomerRequest, idempotency_key: str | None = None) -> Customer: ...
    def page(self, payload: PageCustomersRequest | None = None) -> CustomerPage: ...
