"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from .._models import FileLink, FileLinkCreation, FileLinkPage
from ..request_types import *
from .files import FileDownload

class FileLinks:
    def __init__(self, http: HttpClient) -> None: ...
    def create(self, payload: CreateFileLinkRequest, idempotency_key: str | None = None) -> FileLinkCreation: ...
    def lookup(self, id: str) -> FileLink: ...
    def page(self, payload: PageFileLinksRequest | None = None) -> FileLinkPage: ...
    def revoke(self, payload: RevokeFileLinkRequest, idempotency_key: str | None = None) -> FileLink: ...
    def open(self, url: str, save_to: str | None = None) -> FileDownload: ...
