"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from .._models import File, FilePage
from ..request_types import *

class FileDownload:
    def __init__(self, data: bytes, headers: dict[str, str] | None = None) -> None: ...
    def save_to(self, path: str) -> None: ...

class Files:
    def __init__(self, http: HttpClient) -> None: ...
    def create(self, *, file: str, purpose: str, title: str | None = None, custom_data: dict[str, str] | None = None, idempotency_key: str | None = None) -> File: ...
    def lookup(self, file_id: str) -> File: ...
    def page(self, payload: PageFilesRequest | None = None) -> FilePage: ...
    def contents(self, *, file_id: str, disposition: str = 'attachment') -> FileDownload: ...
    def delete(self, file_id: str) -> File: ...
