"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from .._models import *
from ..request_types import *
from ..response_object import ResponseObject
from .files import FileDownload

class FileLinks:
    def __init__(self, http: HttpClient) -> None: ...
    def create(self, payload: CreateFileLinkRequest, idempotency_key: str | None = None) -> CreateFileLinkResponse: ...
    def lookup(self, id: str) -> FileLinkResponse: ...
    def page(self, payload: PageFileLinksRequest | None = None) -> FileLinkPageResponse: ...
    def revoke(self, payload: RevokeFileLinkRequest, idempotency_key: str | None = None) -> FileLinkResponse: ...
    def open(self, url: str, save_to: str | None = None) -> FileDownload: ...
