"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from .._models import *
from ..request_types import *
from ..response_object import ResponseObject

class FinancialAccounts:
    def __init__(self, http: HttpClient) -> None: ...
    def create(self, payload: FinancialAccountCreateRequest) -> CreateFinancialAccountResponse: ...
    def lookup(self, account_id: str) -> LookupFinancialAccountResponse: ...
    def connect(self, payload: FinancialAccountCreateRequest) -> ConnectFinancialAccountResponse: ...
    def archive(self, payload: FinancialAccountDisableRequest) -> DisconnectFinancialAccountResponse: ...
    def page(self, payload: FinancialAccountPageRequest | None = None) -> PageFinancialAccountsResponse: ...
    def verify(self, payload: FinancialAccountIDRequest) -> LookupFinancialAccountResponse: ...
    def update(self, payload: FinancialAccountUpdateRequest) -> UpdateFinancialAccountResponse: ...
    def enable_push(self, account_id: str) -> EnableFinancialAccountPushResponse: ...
    def disable_push(self, account_id: str, unset_as_payout_destination: bool | None = None) -> DisableFinancialAccountPushResponse: ...
    def disconnect(self, account_id: str, unset_as_payout_destination: bool | None = None) -> DisconnectFinancialAccountResponse: ...
    def reconnect(self, account_id: str) -> ReconnectFinancialAccountResponse: ...
    def enable_pull(self, account_id: str) -> EnableFinancialAccountPullResponse: ...
    def disable_pull(self, account_id: str) -> DisableFinancialAccountPullResponse: ...
