"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from inttegro.financial_account.financial_account import FinancialAccount
from inttegro.financial_account.page import Page
from inttegro.financial_account.id_request import IDRequest
from inttegro.financial_account.page_request import PageRequest
from inttegro.financial_account.update_request import UpdateRequest
from inttegro.financial_account.disable_request import DisableRequest
from inttegro.financial_account.create_request import CreateRequest

class FinancialAccounts:
    def __init__(self, http: HttpClient) -> None: ...
    def create(self, payload: CreateRequest) -> FinancialAccount: ...
    def lookup(self, account_id: str) -> FinancialAccount: ...
    def connect(self, payload: CreateRequest) -> FinancialAccount: ...
    def archive(self, payload: DisableRequest) -> FinancialAccount: ...
    def page(self, payload: PageRequest | None = None) -> Page: ...
    def verify(self, payload: IDRequest) -> FinancialAccount: ...
    def update(self, payload: UpdateRequest) -> FinancialAccount: ...
    def enable_push(self, account_id: str) -> FinancialAccount: ...
    def disable_push(self, account_id: str, unset_as_payout_destination: bool | None = None) -> FinancialAccount: ...
    def disconnect(self, account_id: str, unset_as_payout_destination: bool | None = None) -> FinancialAccount: ...
    def reconnect(self, account_id: str) -> FinancialAccount: ...
    def enable_pull(self, account_id: str) -> FinancialAccount: ...
    def disable_pull(self, account_id: str) -> FinancialAccount: ...
