"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from .._models import FinancialAccount, FinancialAccountPage
from ..request_types import *

class FinancialAccounts:
    def __init__(self, http: HttpClient) -> None: ...
    def create(self, payload: FinancialAccountCreateRequest) -> FinancialAccount: ...
    def lookup(self, account_id: str) -> FinancialAccount: ...
    def connect(self, payload: FinancialAccountCreateRequest) -> FinancialAccount: ...
    def archive(self, payload: FinancialAccountDisableRequest) -> FinancialAccount: ...
    def page(self, payload: FinancialAccountPageRequest | None = None) -> FinancialAccountPage: ...
    def verify(self, payload: FinancialAccountIDRequest) -> FinancialAccount: ...
    def update(self, payload: FinancialAccountUpdateRequest) -> FinancialAccount: ...
    def enable_push(self, account_id: str) -> FinancialAccount: ...
    def disable_push(self, account_id: str, unset_as_payout_destination: bool | None = None) -> FinancialAccount: ...
    def disconnect(self, account_id: str, unset_as_payout_destination: bool | None = None) -> FinancialAccount: ...
    def reconnect(self, account_id: str) -> FinancialAccount: ...
    def enable_pull(self, account_id: str) -> FinancialAccount: ...
    def disable_pull(self, account_id: str) -> FinancialAccount: ...
