"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from .._models import GeneratedSecretKey, SecretKey, SecretKeyPage, SecretKeyUsage
from ..request_types import *

class Keys:
    def __init__(self, http: HttpClient) -> None: ...
    def generate(self, payload: GenerateSecretKeyRequest | None = None) -> GeneratedSecretKey: ...
    def page(self, payload: PageSecretKeysRequest | None = None) -> SecretKeyPage: ...
    def lookup(self, secret_key_id: str) -> SecretKey: ...
    def lookup_with_params(self, payload: LookupSecretKeyRequest) -> SecretKey: ...
    def update(self, payload: UpdateSecretKeyRequest) -> SecretKey: ...
    def destroy(self, secret_key_id: str) -> SecretKey: ...
    def destroy_with_params(self, payload: DestroySecretKeyRequest) -> SecretKey: ...
    def usage(self, payload: SecretKeyUsageRequest | str) -> SecretKeyUsage: ...
