"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from inttegro.secret_key.generated import Generated
from inttegro.secret_key.secret_key import SecretKey
from inttegro.secret_key.page import Page
from inttegro.secret_key.usage import Usage
from inttegro.secret_key.generate_request import GenerateRequest
from inttegro.secret_key.page_request import PageRequest
from inttegro.secret_key.lookup_request import LookupRequest
from inttegro.secret_key.update_request import UpdateRequest
from inttegro.secret_key.destroy_request import DestroyRequest
from inttegro.secret_key.usage_request import UsageRequest

class Keys:
    def __init__(self, http: HttpClient) -> None: ...
    def generate(self, payload: GenerateRequest | None = None) -> Generated: ...
    def page(self, payload: PageRequest | None = None) -> Page: ...
    def lookup(self, secret_key_id: str) -> SecretKey: ...
    def lookup_with_params(self, payload: LookupRequest) -> SecretKey: ...
    def update(self, payload: UpdateRequest) -> SecretKey: ...
    def destroy(self, secret_key_id: str) -> SecretKey: ...
    def destroy_with_params(self, payload: DestroyRequest) -> SecretKey: ...
    def usage(self, payload: UsageRequest | str) -> Usage: ...
