"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from .._models import *
from ..request_types import *
from ..response_object import ResponseObject

class Keys:
    def __init__(self, http: HttpClient) -> None: ...
    def generate(self, payload: GenerateSecretKeyRequest | None = None) -> GenerateSecretKeyResponse: ...
    def page(self, payload: PageSecretKeysRequest | None = None) -> PageSecretKeysResponse: ...
    def lookup(self, secret_key_id: str) -> LookupSecretKeyResponse: ...
    def lookup_with_params(self, payload: LookupSecretKeyRequest) -> LookupSecretKeyResponse: ...
    def update(self, payload: UpdateSecretKeyRequest) -> UpdateSecretKeyResponse: ...
    def destroy(self, secret_key_id: str) -> DestroySecretKeyResponse: ...
    def destroy_with_params(self, payload: DestroySecretKeyRequest) -> DestroySecretKeyResponse: ...
    def usage(self, payload: SecretKeyUsageRequest | str) -> SecretKeyUsageResponse: ...
