"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from .._models import *
from ..request_types import *
from ..response_object import ResponseObject

class MessageTemplates:
    def __init__(self, http: HttpClient) -> None: ...
    def create(self, payload: CreateMessageTemplateRequest, idempotency_key: str | None = None) -> MessageTemplateEnvelope: ...
    def update(self, payload: UpdateMessageTemplateRequest, idempotency_key: str | None = None) -> MessageTemplateEnvelope: ...
    def publish(self, template_id: str, idempotency_key: str | None = None) -> MessageTemplateEnvelope: ...
    def archive(self, template_id: str, idempotency_key: str | None = None) -> MessageTemplateEnvelope: ...
    def lookup(self, template_id: str) -> MessageTemplateEnvelope: ...
    def page(self, payload: PageMessageTemplatesRequest | None = None) -> MessageTemplatesPageEnvelope: ...
    def render_preview(self, payload: RenderMessageTemplatePreviewRequest) -> RenderMessageTemplatePreviewResponse: ...
