"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from inttegro.message_template.message_template import MessageTemplate
from inttegro.message_template.preview import Preview
from inttegro.message_template.page import Page
from inttegro.message_template.update_request import UpdateRequest
from inttegro.message_template.page_request import PageRequest
from inttegro.message_template.render_preview_request import RenderPreviewRequest
from inttegro.message_template.create_request import CreateRequest

class MessageTemplates:
    def __init__(self, http: HttpClient) -> None: ...
    def create(self, payload: CreateRequest, idempotency_key: str | None = None) -> MessageTemplate: ...
    def update(self, payload: UpdateRequest, idempotency_key: str | None = None) -> MessageTemplate: ...
    def publish(self, template_id: str, idempotency_key: str | None = None) -> MessageTemplate: ...
    def archive(self, template_id: str, idempotency_key: str | None = None) -> MessageTemplate: ...
    def lookup(self, template_id: str) -> MessageTemplate: ...
    def page(self, payload: PageRequest | None = None) -> Page: ...
    def render_preview(self, payload: RenderPreviewRequest) -> Preview: ...
