"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from .._models import MessageTemplate, MessageTemplatePreview, MessageTemplatesPage
from ..request_types import *

class MessageTemplates:
    def __init__(self, http: HttpClient) -> None: ...
    def create(self, payload: CreateMessageTemplateRequest, idempotency_key: str | None = None) -> MessageTemplate: ...
    def update(self, payload: UpdateMessageTemplateRequest, idempotency_key: str | None = None) -> MessageTemplate: ...
    def publish(self, template_id: str, idempotency_key: str | None = None) -> MessageTemplate: ...
    def archive(self, template_id: str, idempotency_key: str | None = None) -> MessageTemplate: ...
    def lookup(self, template_id: str) -> MessageTemplate: ...
    def page(self, payload: PageMessageTemplatesRequest | None = None) -> MessageTemplatesPage: ...
    def render_preview(self, payload: RenderMessageTemplatePreviewRequest) -> MessageTemplatePreview: ...
