"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from inttegro.order.order import Order
from inttegro.order.document_delivery_result import DocumentDeliveryResult
from inttegro.order.page import Page
from inttegro.order.update_request import UpdateRequest
from inttegro.order.pay_request import PayRequest
from inttegro.payment.confirm_request import ConfirmRequest
from inttegro.order.complete_request import CompleteRequest
from inttegro.order.document_delivery_request import DocumentDeliveryRequest
from inttegro.order.page_request import PageRequest
from inttegro.order.create_request import CreateRequest

class Orders:
    def __init__(self, http: HttpClient) -> None: ...
    def create(self, payload: CreateRequest) -> Order: ...
    def lookup(self, order_id: str, **options: object) -> Order: ...
    def update(self, payload: UpdateRequest) -> Order: ...
    def pay(self, payload: PayRequest) -> Order: ...
    def confirm_payment(self, payload: ConfirmRequest) -> Order: ...
    def request_confirmation(self, order_id: str, request_meta: dict[str, str] | None = None) -> Order: ...
    def finalize(self, order_id: str, request_meta: dict[str, str] | None = None) -> Order: ...
    def send_invoice(self, payload: DocumentDeliveryRequest) -> DocumentDeliveryResult: ...
    def send_receipt(self, payload: DocumentDeliveryRequest) -> DocumentDeliveryResult: ...
    def complete(self, payload: CompleteRequest) -> Order: ...
    def cancel(self, order_id: str, request_meta: dict[str, str] | None = None) -> Order: ...
    def page(self, payload: PageRequest | None = None) -> Page: ...
