"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from .._models import *
from ..request_types import *
from ..response_object import ResponseObject

class Orders:
    def __init__(self, http: HttpClient) -> None: ...
    def create(self, payload: CreateOrderRequest) -> Order: ...
    def new(self, payload: CreateOrderRequest) -> Order: ...
    def lookup(self, order_id: str, **options: object) -> Order: ...
    def update(self, payload: UpdateOrderRequest) -> Order: ...
    def pay(self, payload: PayOrderRequest) -> Order: ...
    def confirm_payment(self, payload: ConfirmPaymentRequest) -> Order: ...
    def request_confirmation(self, order_id: str, request_meta: dict[str, str] | None = None) -> Order: ...
    def finalize(self, order_id: str, request_meta: dict[str, str] | None = None) -> Order: ...
    def send_invoice(self, payload: OrderDocumentDeliveryRequest) -> OrderDocumentDeliveryResult: ...
    def send_receipt(self, payload: OrderDocumentDeliveryRequest) -> OrderDocumentDeliveryResult: ...
    def complete(self, payload: CompleteOrderRequest) -> Order: ...
    def cancel(self, order_id: str, request_meta: dict[str, str] | None = None) -> Order: ...
    def refund(self, payload: CreateRefundRequest, idempotency_key: str | None = None) -> Refund: ...
    def page(self, payload: PageOrdersRequest | None = None) -> OrderPage: ...
