"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from .._models import OTPTransaction, OTPVerification
from ..request_types import *

class Otp:
    def __init__(self, http: HttpClient) -> None: ...
    def initiate(self, payload: InitiateOTPRequest) -> OTPTransaction: ...
    def verify(self, payload: VerifyOTPRequest) -> OTPVerification: ...
    def lookup(self, payload: LookupOTPRequest) -> OTPTransaction: ...
    def cancel(self, payload: LookupOTPRequest) -> OTPTransaction: ...
