"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from .._models import *
from ..request_types import *
from ..response_object import ResponseObject

class Otp:
    def __init__(self, http: HttpClient) -> None: ...
    def initiate(self, payload: InitiateOTPRequest) -> InitiateOTPResponse: ...
    def verify(self, payload: VerifyOTPRequest) -> VerifyOTPResponse: ...
    def lookup(self, payload: LookupOTPRequest) -> LookupOTPResponse: ...
    def cancel(self, payload: LookupOTPRequest) -> LookupOTPResponse: ...
