"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from inttegro.payment_method.payment_method import PaymentMethod
from inttegro.payment_method.deletion import Deletion
from inttegro.payment_method.page import Page
from inttegro.payment_method.settings import Settings
from inttegro.payment_method.verification_session import VerificationSession
from inttegro.payment_method.tokenize_mobile_money_request import TokenizeMobileMoneyRequest
from inttegro.payment_method.lookup_request import LookupRequest
from inttegro.payment_method.page_request import PageRequest
from inttegro.payment_method.update_request import UpdateRequest

class PaymentMethods:
    def __init__(self, http: HttpClient) -> None: ...
    def tokenize(self, payload: TokenizeMobileMoneyRequest) -> PaymentMethod: ...
    def verify(self, payment_method_id: str, request_meta: dict[str, str] | None = None) -> VerificationSession: ...
    def confirm_verification(self, payload: LookupRequest) -> PaymentMethod: ...
    def lookup(self, payment_method_id: str) -> PaymentMethod: ...
    def page(self, payload: PageRequest | None = None) -> Page: ...
    def update(self, payload: UpdateRequest) -> PaymentMethod: ...
    def activate(self, payment_method_id: str) -> PaymentMethod: ...
    def disactivate(self, payment_method_id: str) -> PaymentMethod: ...
    def deactivate(self, payment_method_id: str) -> PaymentMethod: ...
    def archive(self, payment_method_id: str) -> PaymentMethod: ...
    def unarchive(self, payment_method_id: str) -> PaymentMethod: ...
    def delete(self, payment_method_id: str, request_meta: dict[str, str] | None = None) -> Deletion: ...
    def settings(self) -> Settings: ...
