"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from .._models import PaymentMethod, PaymentMethodDeletion, PaymentMethodPage, PaymentMethodSettings, PaymentMethodVerificationSession
from ..request_types import *

class PaymentMethods:
    def __init__(self, http: HttpClient) -> None: ...
    def tokenize(self, payload: TokenizeMobileMoneyPaymentMethodRequest) -> PaymentMethod: ...
    def verify(self, payment_method_id: str, request_meta: dict[str, str] | None = None) -> PaymentMethodVerificationSession: ...
    def confirm_verification(self, payload: LookupPaymentMethodRequest) -> PaymentMethod: ...
    def lookup(self, payment_method_id: str) -> PaymentMethod: ...
    def page(self, payload: PaymentMethodPageRequest | None = None) -> PaymentMethodPage: ...
    def update(self, payload: UpdatePaymentMethodRequest) -> PaymentMethod: ...
    def activate(self, payment_method_id: str) -> PaymentMethod: ...
    def disactivate(self, payment_method_id: str) -> PaymentMethod: ...
    def deactivate(self, payment_method_id: str) -> PaymentMethod: ...
    def archive(self, payment_method_id: str) -> PaymentMethod: ...
    def unarchive(self, payment_method_id: str) -> PaymentMethod: ...
    def delete(self, payment_method_id: str, request_meta: dict[str, str] | None = None) -> PaymentMethodDeletion: ...
    def settings(self) -> PaymentMethodSettings: ...
