"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from .._models import *
from ..request_types import *
from ..response_object import ResponseObject

class PaymentMethods:
    def __init__(self, http: HttpClient) -> None: ...
    def tokenize(self, payload: TokenizeMobileMoneyPaymentMethodRequest) -> TokenizePaymentMethodResponse: ...
    def verify(self, payment_method_id: str, request_meta: dict[str, str] | None = None) -> LookupPaymentMethodResponse: ...
    def confirm_verification(self, payload: LookupPaymentMethodRequest) -> LookupPaymentMethodResponse: ...
    def lookup(self, payment_method_id: str) -> LookupPaymentMethodResponse: ...
    def page(self, payload: PaymentMethodPageRequest | None = None) -> PaymentMethodPageResponse: ...
    def update(self, payload: UpdatePaymentMethodRequest) -> UpdatePaymentMethodResponse: ...
    def activate(self, payment_method_id: str) -> ActivatePaymentMethodResponse: ...
    def disactivate(self, payment_method_id: str) -> DisactivatePaymentMethodResponse: ...
    def deactivate(self, payment_method_id: str) -> DisactivatePaymentMethodResponse: ...
    def archive(self, payment_method_id: str) -> ArchivePaymentMethodResponse: ...
    def unarchive(self, payment_method_id: str) -> UnarchivePaymentMethodResponse: ...
    def delete(self, payment_method_id: str, request_meta: dict[str, str] | None = None) -> ArchivePaymentMethodResponse: ...
    def settings(self) -> GetPaymentMethodSettingsResponse: ...
