"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from .._models import Payout, PayoutPage, PayoutSettingsLookup, PayoutSettingsMutation
from ..request_types import *

class Payouts:
    def __init__(self, http: HttpClient) -> None: ...
    def set_destinations(self, destinations: SetPayoutDestinationsRequest | dict[str, str]) -> PayoutSettingsMutation: ...
    def settings(self) -> PayoutSettingsLookup: ...
    def schedule(self, payload: SchedulePayoutRequest) -> Payout: ...
    def lookup(self, payout_id: str) -> Payout: ...
    def disable_automatic(self) -> PayoutSettingsMutation: ...
    def enable_automatic(self) -> PayoutSettingsMutation: ...
    def enable_fx(self) -> PayoutSettingsLookup: ...
    def disable_fx(self) -> PayoutSettingsLookup: ...
    def page(self, payload: PagePayoutsRequest | None = None) -> PayoutPage: ...
    def cancel(self, payout_id: str) -> Payout: ...
