"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from inttegro.payout.payout import Payout
from inttegro.payout.page import Page
from inttegro.payout.settings_lookup import SettingsLookup
from inttegro.payout.settings_mutation import SettingsMutation
from inttegro.schedule.payout_request import PayoutRequest
from inttegro.payout.set_destinations_request import SetDestinationsRequest
from inttegro.payout.page_request import PageRequest

class Payouts:
    def __init__(self, http: HttpClient) -> None: ...
    def set_destinations(self, destinations: SetDestinationsRequest | dict[str, str]) -> SettingsMutation: ...
    def settings(self) -> SettingsLookup: ...
    def schedule(self, payload: PayoutRequest) -> Payout: ...
    def lookup(self, payout_id: str) -> Payout: ...
    def disable_automatic(self) -> SettingsMutation: ...
    def enable_automatic(self) -> SettingsMutation: ...
    def enable_fx(self) -> SettingsLookup: ...
    def disable_fx(self) -> SettingsLookup: ...
    def page(self, payload: PageRequest | None = None) -> Page: ...
    def cancel(self, payout_id: str) -> Payout: ...
