"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from .._models import *
from ..request_types import *
from ..response_object import ResponseObject

class Payouts:
    def __init__(self, http: HttpClient) -> None: ...
    def set_destinations(self, destinations: dict[str, str]) -> SetPayoutDestinationsResponse: ...
    def settings(self) -> GetPayoutSettingsResponse: ...
    def schedule(self, payload: SchedulePayoutRequest) -> SchedulePayoutResponse: ...
    def lookup(self, payout_id: str) -> LookupPayoutResponse: ...
    def disable_automatic(self) -> DisableAutomaticPayoutsResponse: ...
    def enable_automatic(self) -> EnableAutomaticPayoutsResponse: ...
    def enable_fx(self) -> GetPayoutSettingsResponse: ...
    def disable_fx(self) -> GetPayoutSettingsResponse: ...
    def page(self, payload: PagePayoutsRequest | None = None) -> PagePayoutsResponse: ...
    def cancel(self, payout_id: str) -> CancelPayoutResponse: ...
