"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from inttegro.price.price import Price
from inttegro.price.page import Page
from inttegro.price.params import Params
from inttegro.price.page_request import PageRequest
from inttegro.price.update_request import UpdateRequest

class Prices:
    def __init__(self, http: HttpClient) -> None: ...
    def create(self, payload: Params) -> Price: ...
    def lookup(self, price_id: str) -> Price: ...
    def page(self, payload: PageRequest | None = None) -> Page: ...
    def update(self, payload: UpdateRequest) -> Price: ...
    def activate(self, price_id: str) -> Price: ...
    def deactivate(self, price_id: str) -> Price: ...
    def archive(self, price_id: str, idempotency_key: str | None = None) -> Price: ...
