"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from .._models import CatalogPrice, PricePage
from ..request_types import *

class Prices:
    def __init__(self, http: HttpClient) -> None: ...
    def create(self, payload: CatalogPriceParams) -> CatalogPrice: ...
    def lookup(self, price_id: str) -> CatalogPrice: ...
    def page(self, payload: PricePageRequest | None = None) -> PricePage: ...
    def update(self, payload: UpdatePriceRequest) -> CatalogPrice: ...
    def activate(self, price_id: str) -> CatalogPrice: ...
    def deactivate(self, price_id: str) -> CatalogPrice: ...
    def archive(self, price_id: str, idempotency_key: str | None = None) -> CatalogPrice: ...
