"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from .._models import *
from ..request_types import *
from ..response_object import ResponseObject

class Prices:
    def __init__(self, http: HttpClient) -> None: ...
    def create(self, payload: CreatePriceRequest) -> PriceResponse: ...
    def lookup(self, price_id: str) -> PriceResponse: ...
    def page(self, payload: PricePageRequest | None = None) -> PricePageResponse: ...
    def update(self, payload: UpdatePriceRequest) -> PriceResponse: ...
    def activate(self, price_id: str) -> PriceResponse: ...
    def deactivate(self, price_id: str) -> PriceResponse: ...
    def archive(self, price_id: str, idempotency_key: str | None = None) -> PriceResponse: ...
