"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from inttegro.price.price import Price
from inttegro.product.product import Product
from inttegro.product.page import Page
from inttegro.product.create_request import CreateRequest
from inttegro.product.add_price_request import AddPriceRequest
from inttegro.product.lookup_request import LookupRequest
from inttegro.product.update_request import UpdateRequest
from inttegro.product.page_request import PageRequest

class Products:
    def __init__(self, http: HttpClient) -> None: ...
    def create(self, payload: CreateRequest) -> Product: ...
    def add_price(self, payload: AddPriceRequest) -> Price: ...
    def set_default_unit_price(self, payload: LookupRequest) -> Product: ...
    def lookup(self, product_id: str) -> Product: ...
    def update(self, payload: UpdateRequest) -> Product: ...
    def publish(self, product_id: str) -> Product: ...
    def unpublish(self, product_id: str) -> Product: ...
    def archive(self, product_id: str) -> Product: ...
    def page(self, payload: PageRequest | None = None) -> Page: ...
