"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from .._models import CatalogPrice, Product, ProductPage
from ..request_types import *

class Products:
    def __init__(self, http: HttpClient) -> None: ...
    def create(self, payload: CreateProductRequest) -> Product: ...
    def add_price(self, payload: AddProductPriceRequest) -> CatalogPrice: ...
    def set_default_unit_price(self, payload: LookupProductRequest) -> Product: ...
    def lookup(self, product_id: str) -> Product: ...
    def update(self, payload: UpdateProductRequest) -> Product: ...
    def publish(self, product_id: str) -> Product: ...
    def unpublish(self, product_id: str) -> Product: ...
    def archive(self, product_id: str) -> Product: ...
    def page(self, payload: PageProductsRequest | None = None) -> ProductPage: ...
