"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from .._models import *
from ..request_types import *
from ..response_object import ResponseObject

class Products:
    def __init__(self, http: HttpClient) -> None: ...
    def create(self, payload: CreateProductRequest) -> ProductResponse: ...
    def add_price(self, payload: AddProductPriceRequest) -> AddProductPriceResponse: ...
    def set_default_unit_price(self, payload: LookupProductRequest) -> ProductResponse: ...
    def lookup(self, product_id: str) -> ProductResponse: ...
    def update(self, payload: UpdateProductRequest) -> UpdateProductResponse: ...
    def publish(self, product_id: str) -> ProductResponse: ...
    def unpublish(self, product_id: str) -> ProductResponse: ...
    def archive(self, product_id: str) -> ProductResponse: ...
    def page(self, payload: PageProductsRequest | None = None) -> PageProductsResponse: ...
