"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from .._models import *
from ..request_types import *
from ..response_object import ResponseObject

class PurchaseIntents:
    def __init__(self, http: HttpClient) -> None: ...
    def create(self, payload: CreatePurchaseIntentRequest) -> PurchaseIntentResponse: ...
    def update(self, payload: UpdatePurchaseIntentRequest) -> PurchaseIntentResponse: ...
    def cancel(self, id: str) -> PurchaseIntentResponse: ...
    def lookup(self, id: str) -> PurchaseIntentResponse: ...
    def page(self, payload: PagePurchaseIntentsRequest) -> PagePurchaseIntentsResponse: ...
