"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from .._models import PurchaseIntent, PurchaseIntentPage
from ..request_types import *

class PurchaseIntents:
    def __init__(self, http: HttpClient) -> None: ...
    def create(self, payload: CreatePurchaseIntentRequest) -> PurchaseIntent: ...
    def update(self, payload: UpdatePurchaseIntentRequest) -> PurchaseIntent: ...
    def cancel(self, id: str) -> PurchaseIntent: ...
    def lookup(self, id: str) -> PurchaseIntent: ...
    def page(self, payload: PagePurchaseIntentsRequest) -> PurchaseIntentPage: ...
