"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from inttegro.purchase_intent.purchase_intent import PurchaseIntent
from inttegro.purchase_intent.page import Page
from inttegro.purchase_intent.create_request import CreateRequest
from inttegro.purchase_intent.update_request import UpdateRequest
from inttegro.purchase_intent.page_request import PageRequest

class PurchaseIntents:
    def __init__(self, http: HttpClient) -> None: ...
    def create(self, payload: CreateRequest) -> PurchaseIntent: ...
    def update(self, payload: UpdateRequest) -> PurchaseIntent: ...
    def cancel(self, id: str) -> PurchaseIntent: ...
    def lookup(self, id: str) -> PurchaseIntent: ...
    def page(self, payload: PageRequest) -> Page: ...
