"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from .._models import Refund, RefundPage
from ..request_types import *

class Refunds:
    def __init__(self, http: HttpClient) -> None: ...
    def create(self, payload: CreateRefundRequest, idempotency_key: str | None = None) -> Refund: ...
    def cancel(self, refund_id: str, idempotency_key: str | None = None) -> Refund: ...
    def lookup(self, refund_id: str) -> Refund: ...
    def page(self, payload: PageRefundsRequest) -> RefundPage: ...
