"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from .._models import *
from ..request_types import *
from ..response_object import ResponseObject

class Refunds:
    def __init__(self, http: HttpClient) -> None: ...
    def create(self, payload: CreateRefundRequest, idempotency_key: str | None = None) -> RefundResponse: ...
    def cancel(self, refund_id: str, idempotency_key: str | None = None) -> RefundResponse: ...
    def lookup(self, refund_id: str) -> RefundResponse: ...
    def page(self, payload: PageRefundsRequest) -> RefundPageResponse: ...
