"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from inttegro.refund.refund import Refund
from inttegro.refund.page import Page
from inttegro.refund.create_request import CreateRequest
from inttegro.refund.page_request import PageRequest

class Refunds:
    def __init__(self, http: HttpClient) -> None: ...
    def create(self, payload: CreateRequest, idempotency_key: str | None = None) -> Refund: ...
    def cancel(self, refund_id: str, idempotency_key: str | None = None) -> Refund: ...
    def lookup(self, refund_id: str) -> Refund: ...
    def page(self, payload: PageRequest) -> Page: ...
