"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from .._models import *
from ..request_types import *
from ..response_object import ResponseObject

class UploadRequests:
    def __init__(self, http: HttpClient) -> None: ...
    def create(self, payload: CreateUploadRequestRequest, idempotency_key: str | None = None) -> UploadRequestResponse: ...
    def lookup(self, id: str) -> UploadRequestWithAttemptResponse: ...
    def page(self, payload: PageUploadRequestsRequest | None = None) -> UploadRequestPageResponse: ...
    def cancel(self, payload: CancelUploadRequestRequest, idempotency_key: str | None = None) -> UploadRequestResponse: ...
    def review(self, payload: ReviewUploadRequestAttemptRequest, idempotency_key: str | None = None) -> UploadRequestWithAttemptResponse: ...
    def fulfill(self, *, upload_url: str, file: str) -> FulfillUploadRequestResponse: ...
