"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from .._models import UploadFulfillment, UploadRequest, UploadRequestPage
from ..request_types import *

class UploadRequests:
    def __init__(self, http: HttpClient) -> None: ...
    def create(self, payload: CreateUploadRequestRequest, idempotency_key: str | None = None) -> UploadRequest: ...
    def lookup(self, id: str) -> UploadRequest: ...
    def page(self, payload: PageUploadRequestsRequest | None = None) -> UploadRequestPage: ...
    def cancel(self, payload: CancelUploadRequestRequest, idempotency_key: str | None = None) -> UploadRequest: ...
    def review(self, payload: ReviewUploadRequestAttemptByIDRequest | ReviewUploadRequestAttemptByOrdinalRequest, idempotency_key: str | None = None) -> UploadRequest: ...
    def fulfill(self, *, upload_url: str, file: str) -> UploadFulfillment: ...
