"""Generated public typing surface. Do not edit by hand."""

from typing import Any

from ..http_client import HttpClient
from inttegro.shared.upload_fulfillment import UploadFulfillment
from inttegro.upload_request.upload_request import UploadRequest
from inttegro.upload_request.page import Page
from inttegro.upload_request.create_request import CreateRequest
from inttegro.upload_request.page_request import PageRequest
from inttegro.upload_request.cancel_request import CancelRequest
from inttegro.upload_request.review_attempt_by_id_request import ReviewAttemptByIDRequest
from inttegro.upload_request.review_attempt_by_ordinal_request import ReviewAttemptByOrdinalRequest

class UploadRequests:
    def __init__(self, http: HttpClient) -> None: ...
    def create(self, payload: CreateRequest, idempotency_key: str | None = None) -> UploadRequest: ...
    def lookup(self, id: str) -> UploadRequest: ...
    def page(self, payload: PageRequest | None = None) -> Page: ...
    def cancel(self, payload: CancelRequest, idempotency_key: str | None = None) -> UploadRequest: ...
    def review(self, payload: ReviewAttemptByIDRequest | ReviewAttemptByOrdinalRequest, idempotency_key: str | None = None) -> UploadRequest: ...
    def fulfill(self, *, upload_url: str, file: str) -> UploadFulfillment: ...
