name: Python SDK Release

on:
  push:
    tags:
      - "python-sdk-v*"
      - "commerce-python-v*"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sdks/python
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Build package
        run: poetry build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: commerce-python-sdk
          path: sdks/python/dist/*
